// seedProducts.ts — Full product seed matching production SQL data.
// Prices: priceMeshOnly / priceStandard / priceFullPack (PHP)
// Run:    npx tsx prisma/seedProducts.ts

import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

function gd(id: string) { return `/api/drive-video?id=${id}`; }

// ── Pricing tiers (from SQL) ───────────────────────────────────────────────
// Characters — Orc entry:        450 / 749 / 999   ← SQL values
// Characters — Orc mid:          540 / 899 / 1199
// NOTE: SQL prices differ from old seed; SQL is authoritative.
// ──────────────────────────────────────────────────────────────────────────

const ALL_TIERS = "mesh_only,standard,full_pack";

const products = [

  // ════════════════════════════════════════════════════════════════════
  //  CHARACTERS — ORC SERIES  (Entry: Orc-01–03)
  // ════════════════════════════════════════════════════════════════════
  {
    id: "seed-orc-01", name: "Orc-01",
    description:     "Low-poly orc warrior. Clean Blender topology, 4K PBR textures. OBJ + FBX included. No rig — ideal for background NPCs and static props.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1125, priceStandard: 1874, priceFullPack: 2499,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: gd("1ApEQgnNAza_uRL9NRRPtCMOurPqKj1VP"),
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("1ApEQgnNAza_uRL9NRRPtCMOurPqKj1VP"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-orc-02", name: "Orc-02",
    description:     "Heavy orc warrior built for front-line combat roles. Broad silhouette, chunky armor design. OBJ + FBX, 4K PBR textures.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1125, priceStandard: 1874, priceFullPack: 2499,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: gd("1SaHl7fGvD2uoy34clB1p2UWT-knWENwl"),
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("1SaHl7fGvD2uoy34clB1p2UWT-knWENwl"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-orc-03", name: "Orc-03",
    description:     "Tribal orc with hand-painted detail and bone accessories. OBJ + FBX, 4K PBR textures. Great for cutscenes and environment dressing.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1125, priceStandard: 1874, priceFullPack: 2499,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: gd("1L_mshqNnDK3rfTHrcds3yApBiY-Wt55i"),
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("1L_mshqNnDK3rfTHrcds3yApBiY-Wt55i"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },

  // ════════════════════════════════════════════════════════════════════
  //  CHARACTERS — ORC SERIES  (Mid: Orc-04–07)
  // ════════════════════════════════════════════════════════════════════
  {
    id: "seed-orc-04", name: "Orc-04",
    description:     "Battle-scarred orc veteran with chipped armor and war paint. OBJ + FBX, 4K PBR. High detail for close-up renders and game cinematics.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1260, priceStandard: 2099, priceFullPack: 2799,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: gd("1cx2sETIft3K7R8NnNPumoLet1pW5It0a"),
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("1cx2sETIft3K7R8NnNPumoLet1pW5It0a"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-orc-05", name: "Orc-05",
    description:     "Shaman orc with ceremonial armor and skull trophies. OBJ + FBX, 4K PBR. Detailed bone accessories and layered cloth.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1260, priceStandard: 2099, priceFullPack: 2799,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: gd("13y5Ixc4gOLRjQM7yNpJPFf9_p1O-5YPX"),
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("13y5Ixc4gOLRjQM7yNpJPFf9_p1O-5YPX"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-orc-06", name: "Orc-06",
    description:     "Armored guard orc — tower shield, full plate. OBJ + FBX, 4K PBR. Designed for defensive tank roles and city gate encounters.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1260, priceStandard: 2099, priceFullPack: 2799,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: gd("1fQJZ68HEZK6hh7k1nmtl2DUAKQBf5-mT"),
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("1fQJZ68HEZK6hh7k1nmtl2DUAKQBf5-mT"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-orc-07", name: "Orc-07",
    description:     "Berserker orc — unarmored, rage-fueled, primal energy. OBJ + FBX, 4K PBR. Dynamic silhouette built for fast attack animations.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1260, priceStandard: 2099, priceFullPack: 2799,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: gd("16-RCaA3WjQjMf1GT0Ad2JrjAhR-U_FyH"),
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("16-RCaA3WjQjMf1GT0Ad2JrjAhR-U_FyH"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },

  // ════════════════════════════════════════════════════════════════════
  //  CHARACTERS — ORC SERIES  (High: Orc-08–11)
  // ════════════════════════════════════════════════════════════════════
  {
    id: "seed-orc-08", name: "Orc-08",
    description:     "Elite orc commander. Fully rigged FBX. 4K PBR textures. Ready for Unity and Unreal. Standard tier includes Idle, Walk, Attack 1.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1350, priceStandard: 2249, priceFullPack: 2999,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/character/orc-08-animation.mp4",
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("1Wjgt2RcRkUrbxEMnLQWWdiUdQ3OHwpx3"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-orc-09", name: "Orc-09",
    description:     "Scout orc built for speed and stealth. Fully rigged FBX. Animations: Idle, Walk, Attack 1. 4K PBR textures. Unity/Unreal ready.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1350, priceStandard: 2249, priceFullPack: 2999,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/character/orc-09-animation.mp4",
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("1JB-kYyq0XMrPe0pgrh5L2S-nGmK-wvXE"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-orc-10", name: "Orc-10",
    description:     "Orc warchief with elaborate horned crown and layered armor. Fully rigged FBX. Animations: Idle, Walk, Attack 1. 4K PBR. Unity/Unreal compatible.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1350, priceStandard: 2249, priceFullPack: 2999,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/character/orc-10-animation.mp4",
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("1q3rW69QWjYEK5T53rRTpTFlR7X9ZERRe"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-orc-11", name: "Orc-11",
    description:     "Siege orc built to break walls — heavy plate and giant pauldrons. Fully rigged FBX. Animations: Idle, Walk, Ground Slam. 4K PBR. Unity/Unreal ready.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1350, priceStandard: 2249, priceFullPack: 2999,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/character/orc-11-animation.mp4",
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("1CTk71XmBB9yNz9Osbfd-YHg9mrsgmZkf"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },

  // ════════════════════════════════════════════════════════════════════
  //  CHARACTERS — ORC SERIES  (Premium: Orc-12, Legendary: Orc-13)
  // ════════════════════════════════════════════════════════════════════
  {
    id: "seed-orc-12", name: "Orc-12",
    description:     "Dark shaman orc — glowing rune engravings, tattered robes, bone staff. Full pack: OBJ + FBX rigged + face PNG. Animation slots ready. 4K PBR.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1485, priceStandard: 2474, priceFullPack: 3299,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/character/orc-12-animation.mp4",
    facePngUrl: gd("1ai8U8_LmCzgaZHITTUJ9J6FEUjUdwE61"), threeDUrl: null,
    actionOneUrl: gd("1ZPSoWhJc0ukVny9sCKp0-ytzTsz0aL50"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-orc-13", name: "Orc-13",
    description:     "Legendary orc hero — apex of the orc series. Full cinematic quality, intricate gold-and-iron armor. Full pack: OBJ + FBX rigged + face PNG. 4K PBR.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1575, priceStandard: 2624, priceFullPack: 3499,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/character/orc-13-animation.mp4",
    facePngUrl: gd("1uRu_SW840F9l8UqHlLYh85d60z91qQWM"), threeDUrl: null,
    actionOneUrl: gd("1W1eHcST6_noKH3VCygvpKz-JFZkCF6Su"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },

  // ════════════════════════════════════════════════════════════════════
  //  CHARACTERS — CYBORG SERIES  (Cyborg-01–06)
  // ════════════════════════════════════════════════════════════════════
  {
    id: "seed-cyborg-01", name: "Cyborg-01",
    description:     "AI-generated cyborg character with sleek chrome plating and blue LED accents. OBJ + FBX, 4K PBR textures. High-detail surface for close-up renders and game cinematics.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1440, priceStandard: 2399, priceFullPack: 3199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/character/cyborg-01-animation.mp4",
    facePngUrl: gd("1z_tv87eXQ3VpPBDts-pemYTYc0IVp2CW"), threeDUrl: null,
    actionOneUrl: gd("1_0nDq8ZV_p77DunIBBUqNShtd7sPUaM3"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-cyborg-02", name: "Cyborg-02",
    description:     "Tactical cyborg unit — reinforced shoulder armor, dual sensor eyes, matte-black finish. OBJ + FBX, 4K PBR textures. Built for military and sci-fi game environments.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1440, priceStandard: 2399, priceFullPack: 3199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/character/cyborg-02-animation.mp4",
    facePngUrl: gd("1EdznDR_XhYWhEdoHrvm9Pj6inU3kXLj_"), threeDUrl: null,
    actionOneUrl: gd("1XoKJxcm-L7UXQXvXFkF18Gfrn032i1Qt"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-cyborg-03", name: "Cyborg-03",
    description:     "Stealth cyborg with angular frame, cloaking panel detail, and red visor. OBJ + FBX, 4K PBR textures. Optimized for infiltration and assassin-class game builds.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1440, priceStandard: 2399, priceFullPack: 3199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/character/cyborg-03-animation.mp4",
    facePngUrl: gd("172xNVeWgDKRBgKjYwqDvP1ZcHR-I6qr9"), threeDUrl: null,
    actionOneUrl: gd("1MeLcVZHKHlmgxqa_bNZnkGFymEkyj3mo"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-cyborg-04", name: "Cyborg-04",
    description:     "Heavy combat cyborg — oversized arms, gatling mount on right shoulder, battle-worn plating. OBJ + FBX, 4K PBR textures. Designed for tank and siege roles in sci-fi games.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1440, priceStandard: 2399, priceFullPack: 3199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/character/cyborg-04-animation.mp4",
    facePngUrl: gd("1mG-1wnFRDtfG0kD7C9ycGYW6KzToWO7J"), threeDUrl: null,
    actionOneUrl: gd("1u5a6AfT-k9iL1s4IsGGj1W_lsAULBQTv"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-cyborg-05", name: "Cyborg-05",
    description:     "Medic cyborg — sleek white-and-gold design with biotech scanner arm and holographic HUD. OBJ + FBX, 4K PBR textures. Support class character for sci-fi RPG and strategy games.",
    category:        "character" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   1440, priceStandard: 2399, priceFullPack: 3199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/character/cyborg-05-animation.mp4",
    facePngUrl: gd("1Sifbx4X931_lee8vd4uVg8x0LzXmL7Gm"), threeDUrl: null,
    actionOneUrl: gd("1Heyn0W6pJdiCHMsEzxGyW05afKmQ1dql"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-cyborg-06", name: "Cyborg-06",
    description:     "Rogue cyborg — asymmetric design, exposed wiring, cracked faceplate with glowing core. OBJ + FBX, 4K PBR textures. Villain and antagonist archetype for dark sci-fi narratives.",
    category:        "character" as const, packageTier: "mesh_only" as const,
    priceMeshOnly:   1440, priceStandard: 2399, priceFullPack: 3199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/character/cyborg-06-animation.mp4",
    facePngUrl: gd("1bthqtLgJXwuJ7ADX14m1ZSdN850Sfnmy"), threeDUrl: null,
    actionOneUrl: gd("1bJgokl67ZfUQmn8JGoS5mU1EzjZ-MSbk"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },

  // ════════════════════════════════════════════════════════════════════
  //  WEAPONS — AXE SERIES
  // ════════════════════════════════════════════════════════════════════
  {
    id: "seed-axe-01", name: "Axe-01",
    description:     "Standard battle axe — single blade, iron head, hardwood haft. Clean PBR textures. OBJ + FBX. Ideal for warrior and grunt inventory systems.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   450, priceStandard: 749, priceFullPack: 999,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: gd("1NrTbKznn-3pcIC9q-BqBa2lUfMUsGKa8"),
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("1NrTbKznn-3pcIC9q-BqBa2lUfMUsGKa8"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-axe-02", name: "Axe-02",
    description:     "Dual-blade axe with mirrored crescent heads and wrapped grip. OBJ + FBX, 4K PBR. Good for high-tier loot tables and elite enemies.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   450, priceStandard: 749, priceFullPack: 999,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: gd("1db1EOrzdG2phPiaJ8DJV9Tz1-bfYwB67"),
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("1db1EOrzdG2phPiaJ8DJV9Tz1-bfYwB67"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-axe-03", name: "Axe-03",
    description:     "Ornate ceremonial axe with engraved runes and gold inlay. OBJ + FBX, 4K PBR. Perfect for quest reward weapons and hero character loadouts.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   540, priceStandard: 899, priceFullPack: 1199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: gd("1ZPhiN56sAU9EQIlrrTPY3OSDBhijtHld"),
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("1ZPhiN56sAU9EQIlrrTPY3OSDBhijtHld"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-axe-04", name: "Axe-04",
    description:     "Heavy war axe — oversized blade for two-handed wielding. OBJ + FBX, 4K PBR. Designed for slow, devastating overhead attack animations.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   540, priceStandard: 899, priceFullPack: 1199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/weapon/axe-04-animation.mp4",
    facePngUrl: gd("191hkDNrvVb_son8usIDm31iOrgBmkvfR"), threeDUrl: null,
    actionOneUrl: gd("1jjU-r5EawMDjzhbJueiadCMjkcCZrHtr"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-axe-05", name: "Axe-05",
    description:     "Rune-carved axe with glowing blue engravings and ember texture detail. OBJ + FBX, 4K PBR. High visual impact for magic-class builds.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   540, priceStandard: 899, priceFullPack: 1199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/weapon/axe-05-animation.mp4",
    facePngUrl: gd("13x5-8l_LUKQACSPVcfJ_jlqnl97ezkHs"), threeDUrl: null,
    actionOneUrl: gd("1vl3KhBI_UQIugyIXeBTduabrOh0eZSU5"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-axe-06", name: "Axe-06",
    description:     "Berserker axe — jagged edge, dark iron, blood-stained texture. OBJ + FBX, 4K PBR. High-detail close-up geometry for first-person game views.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   540, priceStandard: 899, priceFullPack: 1199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/weapon/axe-06-animation.mp4",
    facePngUrl: gd("12DeQW_HEs9u4C1CgdVfUX9MuO1hgnU5R"), threeDUrl: null,
    actionOneUrl: gd("1DcmVwUgfOzvl8wzJJOq-YP7pR_8ZXZ4u"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-axe-07", name: "Axe-07",
    description:     "Twin axe set — matched pair with worn leather grip and chain link connector. OBJ + FBX, 4K PBR. Designed for dual-wield combat builds.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   540, priceStandard: 899, priceFullPack: 1199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/weapon/axe-07-animation.mp4",
    facePngUrl: gd("173MzRY8-olUn8e1vCVUSb8KYwlqb13NJ"), threeDUrl: null,
    actionOneUrl: gd("1k9AhDcIY-Em7Wyl5fd2i79DomElK1DnM"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-axe-08", name: "Axe-08",
    description:     "Legendary axe — particle-effect blade with ember and smoke trails on swing. OBJ + FBX, 4K PBR. Premium detail for final boss and legendary loot drops.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   720, priceStandard: 1199, priceFullPack: 1599,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/weapon/axe-08-animation.mp4",
    facePngUrl: gd("1Wy03DzMSKOGtiPn9lFxTs70BFIRm9Y8_"), threeDUrl: null,
    actionOneUrl: gd("1tqcYpL3wqMpomBiXOo_N6yDwspdEgmWu"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },

  // ════════════════════════════════════════════════════════════════════
  //  WEAPONS — HAMMER SERIES
  // ════════════════════════════════════════════════════════════════════
  {
    id: "seed-hammer-01", name: "Hammer-01",
    description:     "War hammer with flanged iron head and worn oak haft. OBJ + FBX, 4K PBR. Solid choice for paladin, blacksmith, and siege roles.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   450, priceStandard: 749, priceFullPack: 999,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/weapon/hammer-01-animation.mp4",
    facePngUrl: gd("1pUpYd4avzD5yMiBVihzqUaPVR0mkkr_0"), threeDUrl: null,
    actionOneUrl: gd("1rOZz4JdPpbII8L68TkmPxCNrKhC0Bnax"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-hammer-02", name: "Hammer-02",
    description:     "Thunder hammer — electrified head with crackling lightning effect on impact. OBJ + FBX, 4K PBR. Premium detail for divine and storm-class builds.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   540, priceStandard: 899, priceFullPack: 1199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/weapon/hammer-02-animation.mp4",
    facePngUrl: gd("1JTHUTad7BP3tuN0S-ySS8achzpMYMOgc"), threeDUrl: null,
    actionOneUrl: gd("1vzptVR7H_6LP5mt_n_8d9I1SBXggylAF"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },

  // ════════════════════════════════════════════════════════════════════
  //  WEAPONS — SWORD SERIES  (Sword-01–04)
  // ════════════════════════════════════════════════════════════════════
  {
    id: "seed-sword-01", name: "Sword-01",
    description:     "Elegant longsword with tapered double-edge blade and ornate crossguard. OBJ + FBX, 4K PBR textures. Classic knight-class weapon for fantasy RPG and action games.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   540, priceStandard: 899, priceFullPack: 1199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/weapon/sw-01-animation.mp4",
    facePngUrl: gd("1kvKu22j4gtmFu_fTmHcCrsUFCAka0EVx"), threeDUrl: null,
    actionOneUrl: gd("1Y1Ww0jOlGAPUA9Y7I7BAjLh1ymezppww"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-sword-02", name: "Sword-02",
    description:     "Short sword with wide fuller and reinforced tip — designed for fast close-range combat. OBJ + FBX, 4K PBR textures. Great for rogue and duelist character builds.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   540, priceStandard: 899, priceFullPack: 1199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/weapon/sw-02-animation.mp4",
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("1ejAoS0nlpyGCBw-t7pvJ3bQ1GAXBXuIm"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-sword-03", name: "Sword-03",
    description:     "Broad sword with double-edged blade and ornate crossguard. OBJ + FBX, 4K PBR. Clean slash geometry ideal for combo attack and parry animations.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   540, priceStandard: 899, priceFullPack: 1199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/weapon/sw-03-animation.mp4",
    facePngUrl: null, threeDUrl: null,
    actionOneUrl: gd("15BTm6HFoc8WUHpAbIucC1LBHY7M_bs5r"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },
  {
    id: "seed-sword-04", name: "Sword-04",
    description:     "Curved scimitar with engraved blade and jeweled pommel. OBJ + FBX, 4K PBR textures. High visual impact for desert warrior and merchant prince character archetypes.",
    category:        "weapon" as const, packageTier: "full_pack" as const,
    priceMeshOnly:   540, priceStandard: 899, priceFullPack: 1199,
    enabledTiers:    ALL_TIERS,
    isLatest: false, isActive: true,
    previewVideoUrl: "https://pub-2ce00f29dc8e495183023b1ecef335df.r2.dev/weapon/sw-04-animation.mp4",
    facePngUrl: gd("1NGRpRs03SvU6Xw6AUzqExUpdxYU2ZY4i"), threeDUrl: null,
    actionOneUrl: gd("1TM7JZY55zR5JNHW3TxFzcOLX6r3AXDgz"),
    actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null,
    fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null,
    animIdleUrl: null, animWalkUrl: null, animRunUrl: null,
    animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null,
    mediaDriveIds: null,
  },

  // ════════════════════════════════════════════════════════════════════
  //  ARCHITECTURE — EXTERIOR  (Exterior Design 01–05)
  // ════════════════════════════════════════════════════════════════════
  { id: "seed-exterior-design-01", name: "Exterior Design 01", description: "AI-generated exterior architectural visualization. Cinematic lighting, photorealistic materials.", category: "exterior" as const, packageTier: "mesh_only" as const, priceMeshOnly: 225, priceStandard: 374, priceFullPack: 499, enabledTiers: ALL_TIERS, isLatest: false, isActive: true, previewVideoUrl: gd("1kp23x5YBnWovDamPDT2FS00d1ID9SB0k"), facePngUrl: null, threeDUrl: null, actionOneUrl: null, actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null, fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null, animIdleUrl: null, animWalkUrl: null, animRunUrl: null, animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null, mediaDriveIds: null },
  { id: "seed-exterior-design-02", name: "Exterior Design 02", description: "AI-generated exterior architectural visualization. Cinematic lighting, photorealistic materials.", category: "exterior" as const, packageTier: "mesh_only" as const, priceMeshOnly: 225, priceStandard: 374, priceFullPack: 499, enabledTiers: ALL_TIERS, isLatest: false, isActive: true, previewVideoUrl: gd("10CfcifgZBQMoxK2L_ANH8TJ8vUj7v26T"), facePngUrl: null, threeDUrl: null, actionOneUrl: null, actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null, fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null, animIdleUrl: null, animWalkUrl: null, animRunUrl: null, animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null, mediaDriveIds: null },
  { id: "seed-exterior-design-03", name: "Exterior Design 03", description: "AI-generated exterior architectural visualization. Cinematic lighting, photorealistic materials.", category: "exterior" as const, packageTier: "mesh_only" as const, priceMeshOnly: 225, priceStandard: 374, priceFullPack: 499, enabledTiers: ALL_TIERS, isLatest: false, isActive: true, previewVideoUrl: gd("1uK7a0BedMTfGWeZ17WxJt-YYKAJL3bZJ"), facePngUrl: null, threeDUrl: null, actionOneUrl: null, actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null, fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null, animIdleUrl: null, animWalkUrl: null, animRunUrl: null, animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null, mediaDriveIds: null },
  { id: "seed-exterior-design-04", name: "Exterior Design 04", description: "AI-generated exterior architectural visualization. Cinematic lighting, photorealistic materials.", category: "exterior" as const, packageTier: "mesh_only" as const, priceMeshOnly: 225, priceStandard: 374, priceFullPack: 499, enabledTiers: ALL_TIERS, isLatest: false, isActive: true, previewVideoUrl: gd("1On-oICTEgx81tNSRyW7DZYk3IOEDBiAT"), facePngUrl: null, threeDUrl: null, actionOneUrl: null, actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null, fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null, animIdleUrl: null, animWalkUrl: null, animRunUrl: null, animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null, mediaDriveIds: null },
  { id: "seed-exterior-design-05", name: "Exterior Design 05", description: "AI-generated architectural cinematic exterior. Dramatic angles, photorealistic render.", category: "exterior" as const, packageTier: "mesh_only" as const, priceMeshOnly: 225, priceStandard: 374, priceFullPack: 499, enabledTiers: ALL_TIERS, isLatest: false, isActive: true, previewVideoUrl: gd("1MJR8A38OCNRDxb_jRheBdRgexnAOugZf"), facePngUrl: null, threeDUrl: null, actionOneUrl: null, actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null, fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null, animIdleUrl: null, animWalkUrl: null, animRunUrl: null, animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null, mediaDriveIds: null },

  // ════════════════════════════════════════════════════════════════════
  //  ARCHITECTURE — INTERIOR  (Interior Design 01–07)
  // ════════════════════════════════════════════════════════════════════
  { id: "seed-interior-design-01", name: "Interior Design 01", description: "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.", category: "interior" as const, packageTier: "mesh_only" as const, priceMeshOnly: 225, priceStandard: 374, priceFullPack: 499, enabledTiers: ALL_TIERS, isLatest: false, isActive: true, previewVideoUrl: gd("16IlbksfqFgAsIUlIbSnfG1k0miktYC0d"), facePngUrl: null, threeDUrl: null, actionOneUrl: null, actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null, fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null, animIdleUrl: null, animWalkUrl: null, animRunUrl: null, animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null, mediaDriveIds: null },
  { id: "seed-interior-design-02", name: "Interior Design 02", description: "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.", category: "interior" as const, packageTier: "mesh_only" as const, priceMeshOnly: 225, priceStandard: 374, priceFullPack: 499, enabledTiers: ALL_TIERS, isLatest: false, isActive: true, previewVideoUrl: gd("1cHTTgKBilMBXIrIGuSqB2tAb4A9WdobJ"), facePngUrl: null, threeDUrl: null, actionOneUrl: null, actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null, fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null, animIdleUrl: null, animWalkUrl: null, animRunUrl: null, animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null, mediaDriveIds: null },
  { id: "seed-interior-design-03", name: "Interior Design 03", description: "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.", category: "interior" as const, packageTier: "mesh_only" as const, priceMeshOnly: 225, priceStandard: 374, priceFullPack: 499, enabledTiers: ALL_TIERS, isLatest: false, isActive: true, previewVideoUrl: gd("1A9sgWrWpi_Jq2NWZIH5mkh2XP491_2Ce"), facePngUrl: null, threeDUrl: null, actionOneUrl: null, actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null, fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null, animIdleUrl: null, animWalkUrl: null, animRunUrl: null, animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null, mediaDriveIds: null },
  { id: "seed-interior-design-04", name: "Interior Design 04", description: "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.", category: "interior" as const, packageTier: "mesh_only" as const, priceMeshOnly: 225, priceStandard: 374, priceFullPack: 499, enabledTiers: ALL_TIERS, isLatest: false, isActive: true, previewVideoUrl: gd("1sr1O1HBL-q0oFZ2mfhgI3Zf3Y_AWmOzl"), facePngUrl: null, threeDUrl: null, actionOneUrl: null, actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null, fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null, animIdleUrl: null, animWalkUrl: null, animRunUrl: null, animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null, mediaDriveIds: null },
  { id: "seed-interior-design-05", name: "Interior Design 05", description: "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.", category: "interior" as const, packageTier: "mesh_only" as const, priceMeshOnly: 225, priceStandard: 374, priceFullPack: 499, enabledTiers: ALL_TIERS, isLatest: false, isActive: true, previewVideoUrl: gd("1wQtULgqst4SX2imqwdEhnqYRgzcPWJiu"), facePngUrl: null, threeDUrl: null, actionOneUrl: null, actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null, fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null, animIdleUrl: null, animWalkUrl: null, animRunUrl: null, animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null, mediaDriveIds: null },
  { id: "seed-interior-design-06", name: "Interior Design 06", description: "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.", category: "interior" as const, packageTier: "mesh_only" as const, priceMeshOnly: 225, priceStandard: 374, priceFullPack: 499, enabledTiers: ALL_TIERS, isLatest: false, isActive: true, previewVideoUrl: gd("1iqOFR1-0gO4v-Wk7PzBKZ2TsSeL0qoOW"), facePngUrl: null, threeDUrl: null, actionOneUrl: null, actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null, fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null, animIdleUrl: null, animWalkUrl: null, animRunUrl: null, animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null, mediaDriveIds: null },
  { id: "seed-interior-design-07", name: "Interior Design 07", description: "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.", category: "interior" as const, packageTier: "mesh_only" as const, priceMeshOnly: 225, priceStandard: 374, priceFullPack: 499, enabledTiers: ALL_TIERS, isLatest: false, isActive: true, previewVideoUrl: gd("1p34uCYAykKSH9c5fHXh1PuRn_S5XS3sG"), facePngUrl: null, threeDUrl: null, actionOneUrl: null, actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null, fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null, animIdleUrl: null, animWalkUrl: null, animRunUrl: null, animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null, mediaDriveIds: null },

  // ════════════════════════════════════════════════════════════════════
  //  ARCHITECTURE — TIMELAPSE
  // ════════════════════════════════════════════════════════════════════
  { id: "seed-house-build-timelapse-01", name: "House Build Timelapse 01", description: "Full AI-generated house construction timelapse — exterior to interior reveal. Cinematic camera work, photorealistic render throughout.", category: "interior" as const, packageTier: "mesh_only" as const, priceMeshOnly: 360, priceStandard: 599, priceFullPack: 799, enabledTiers: ALL_TIERS, isLatest: false, isActive: true, previewVideoUrl: gd("1-V_JEJtAQvcl6FuldAxpFUFCUV9qwo5Q"), facePngUrl: null, threeDUrl: null, actionOneUrl: null, actionTwoUrl: null, actionThreeUrl: null, actionFourUrl: null, actionFiveUrl: null, actionSixUrl: null, actionSevenUrl: null, fileKeyObj: null, fileKeyFbx: null, fileKeyGlb: null, animIdleUrl: null, animWalkUrl: null, animRunUrl: null, animAttackOneUrl: null, animAttackTwoUrl: null, animDeathUrl: null, animHitUrl: null, mediaDriveIds: null },

];

async function main() {
  console.log("── Total wipe: deleting all existing products ──");
  await prisma.product.deleteMany({});
  console.log("✓ All products deleted.\n");

  console.log(`── Seeding ${products.length} products ──`);
  for (const p of products) {
    const { id, ...data } = p;
    await prisma.product.create({ data: { id, ...data } });
    console.log(`✓ ${p.name}  ₱${p.priceMeshOnly}/${p.priceStandard}/${p.priceFullPack}  [${p.packageTier}]`);
  }
  console.log(`\n✓ Done. ${products.length} products seeded.`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());