// seedProducts.ts — Seeds the Product table with all GDrive assets.
// Prices, tiers, and descriptions reflect the pricing strategy agreed on May 2026.
// Run: npx tsx prisma/seedProducts.ts

import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

// Constructs the drive-video proxy URL so <video src> can stream directly.
function gd(id: string) {
  return `/api/drive-video?id=${id}`;
}

// gimg — direct Drive image URL for face PNGs (served as static image, not proxied video)
function gimg(id: string) {
  return `/api/drive-video?id=${id}`;
}

const products = [

  // ════════════════════════════════════════════════════════════════════════
  //  CHARACTERS — ORC SERIES
  //  Tier:     mesh_only  → ₱899–₱999   (OBJ + FBX, no rig, no anims)
  //  Tier:     standard   → ₱1,800      (rigged + 3 anims: idle, walk, attack)
  //  Tier:     full_pack  → ₱2,500–₱3,200 (rigged + all anims + face PNG)
  // ════════════════════════════════════════════════════════════════════════

  {
    name:            "Orc-01",
    description:     "Low-poly orc warrior. Clean Blender topology, 4K PBR textures. OBJ + FBX included. No rig — ideal for background NPCs and static props.",
    price:           899,
    category:        "character" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1ApEQgnNAza_uRL9NRRPtCMOurPqKj1VP"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1ApEQgnNAza_uRL9NRRPtCMOurPqKj1VP"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Orc-02",
    description:     "Heavy orc warrior built for front-line combat roles. Broad silhouette, chunky armor design. OBJ + FBX, 4K PBR textures. No rig.",
    price:           899,
    category:        "character" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1SaHl7fGvD2uoy34clB1p2UWT-knWENwl"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1SaHl7fGvD2uoy34clB1p2UWT-knWENwl"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Orc-03",
    description:     "Tribal orc with hand-painted detail and bone accessories. OBJ + FBX, 4K PBR textures. No rig. Great for cutscenes and environment dressing.",
    price:           899,
    category:        "character" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1L_mshqNnDK3rfTHrcds3yApBiY-Wt55i"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1L_mshqNnDK3rfTHrcds3yApBiY-Wt55i"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Orc-04",
    description:     "Battle-scarred orc veteran with chipped armor and war paint. OBJ + FBX, 4K PBR. No rig. High detail for close-up renders and game cinematics.",
    price:           999,
    category:        "character" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1cx2sETIft3K7R8NnNPumoLet1pW5It0a"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1cx2sETIft3K7R8NnNPumoLet1pW5It0a"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Orc-05",
    description:     "Orc shaman with ceremonial robes and staff accessory. OBJ + FBX, 4K PBR. No rig. Ideal for RPG support-class roles and lore scenes.",
    price:           999,
    category:        "character" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1-n33tw86ViaKB6xzM0UuCrgF45JVc63-"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1-n33tw86ViaKB6xzM0UuCrgF45JVc63-"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Orc-06",
    description:     "Armored orc guard with tower shield and full plate. OBJ + FBX, 4K PBR. No rig. Built for castle defense and dungeon-gate roles.",
    price:           999,
    category:        "character" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1XVymFPXK8aQa-Ud7DwpkaQ6g3BrGiLjH"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1XVymFPXK8aQa-Ud7DwpkaQ6g3BrGiLjH"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Orc-07",
    description:     "Berserker orc with torn cloth and exposed muscles. OBJ + FBX, 4K PBR. No rig. High-energy design for boss and elite enemy roles.",
    price:           999,
    category:        "character" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("16-RCaA3WjQjMf1GT0Ad2JrjAhR-U_FyH"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("16-RCaA3WjQjMf1GT0Ad2JrjAhR-U_FyH"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },

  // ── Standard tier — rigged + 3 animations (idle, walk, attack 1) ────────

  {
    name:            "Orc-08",
    description:     "Elite orc commander. Fully rigged FBX with 3 hand-keyed animations: Idle loop, Walk cycle, Attack 1. 4K PBR textures. Ready for Unity and Unreal.",
    price:           1800,
    category:        "character" as const,
    packageTier:     "standard" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1Wjgt2RcRkUrbxEMnLQWWdiUdQ3OHwpx3"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1Wjgt2RcRkUrbxEMnLQWWdiUdQ3OHwpx3"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Orc-09",
    description:     "Scout orc built for speed and stealth. Fully rigged FBX with 3 hand-keyed animations: Idle, Walk, Attack 1. 4K PBR textures. Unity/Unreal ready.",
    price:           1800,
    category:        "character" as const,
    packageTier:     "standard" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1JB-kYyq0XMrPe0pgrh5L2S-nGmK-wvXE"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1JB-kYyq0XMrPe0pgrh5L2S-nGmK-wvXE"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Orc-10",
    description:     "Orc warchief with elaborate horned crown and layered armor. Fully rigged FBX. Animations: Idle, Walk, Attack 1. 4K PBR. Unity/Unreal compatible.",
    price:           1800,
    category:        "character" as const,
    packageTier:     "standard" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1q3rW69QWjYEK5T53rRTpTFlR7X9ZERRe"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1q3rW69QWjYEK5T53rRTpTFlR7X9ZERRe"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Orc-11",
    description:     "Siege orc built to break walls — heavy plate and giant pauldrons. Fully rigged FBX. Animations: Idle, Walk, Ground Slam. 4K PBR. Unity/Unreal ready.",
    price:           1800,
    category:        "character" as const,
    packageTier:     "standard" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1CTk71XmBB9yNz9Osbfd-YHg9mrsgmZkf"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1CTk71XmBB9yNz9Osbfd-YHg9mrsgmZkf"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },

  // ── Full pack tier — rigged + face PNG ──────────────────────────────────

  {
    name:            "Orc-12",
    description:     "Dark shaman orc — glowing rune engravings, tattered robes, bone staff. Full pack: OBJ + FBX rigged + face PNG. Animation slots ready for Idle, Walk, Cast, Hit. 4K PBR.",
    price:           2500,
    category:        "character" as const,
    packageTier:     "full_pack" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1ZPSoWhJc0ukVny9sCKp0-ytzTsz0aL50"),
    facePngUrl:      gimg("1ai8U8_LmCzgaZHITTUJ9J6FEUjUdwE61"),
    threeDUrl:       null,
    actionOneUrl:    gd("1ZPSoWhJc0ukVny9sCKp0-ytzTsz0aL50"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Orc-13",
    description:     "Legendary orc hero — the apex of the orc series. Full cinematic quality, intricate gold-and-iron armor, hand-keyed animations. Full pack: OBJ + FBX rigged + face PNG. 4K PBR.",
    price:           3200,
    category:        "character" as const,
    packageTier:     "full_pack" as const,
    isLatest:        true,
    isActive:        true,
    previewVideoUrl: gd("1W1eHcST6_noKH3VCygvpKz-JFZkCF6Su"),
    facePngUrl:      gimg("1uRu_SW840F9l8UqHlLYh85d60z91qQWM"),
    threeDUrl:       null,
    actionOneUrl:    gd("1W1eHcST6_noKH3VCygvpKz-JFZkCF6Su"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },

  // ════════════════════════════════════════════════════════════════════════
  //  WEAPONS — AXE / HAMMER / SWORD SERIES
  //  Tier:  mesh_only  → ₱699–₱899  (OBJ + FBX, textured, no anim)
  //  Tier:  standard   → ₱999–₱1,200 (OBJ + FBX + swing/impact anims)
  // ════════════════════════════════════════════════════════════════════════

  {
    name:            "Axe-01",
    description:     "Standard battle axe — single blade, iron head, hardwood haft. Clean PBR textures. OBJ + FBX. Ideal for warrior and grunt inventory systems.",
    price:           699,
    category:        "weapon" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1NrTbKznn-3pcIC9q-BqBa2lUfMUsGKa8"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1NrTbKznn-3pcIC9q-BqBa2lUfMUsGKa8"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Axe-02",
    description:     "Dual-blade axe with mirrored crescent heads and wrapped grip. OBJ + FBX, 4K PBR. No animations. Good for high-tier loot tables and elite enemies.",
    price:           699,
    category:        "weapon" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1db1EOrzdG2phPiaJ8DJV9Tz1-bfYwB67"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1db1EOrzdG2phPiaJ8DJV9Tz1-bfYwB67"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Axe-03",
    description:     "Ornate ceremonial axe with engraved runes and gold inlay. OBJ + FBX, 4K PBR. No rig. Perfect for quest reward weapons and hero character loadouts.",
    price:           799,
    category:        "weapon" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1ZPhiN56sAU9EQIlrrTPY3OSDBhijtHld"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1ZPhiN56sAU9EQIlrrTPY3OSDBhijtHld"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Axe-04",
    description:     "Heavy war axe — oversized blade for two-handed wielding. OBJ + FBX, 4K PBR. No rig. Designed for slow, devastating overhead attack animations.",
    price:           799,
    category:        "weapon" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1jjU-r5EawMDjzhbJueiadCMjkcCZrHtr"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1jjU-r5EawMDjzhbJueiadCMjkcCZrHtr"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Axe-05",
    description:     "Rune-carved axe with glowing blue engravings and ember texture detail. OBJ + FBX, 4K PBR. No rig. High visual impact for magic-class builds.",
    price:           899,
    category:        "weapon" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1vl3KhBI_UQIugyIXeBTduabrOh0eZSU5"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1vl3KhBI_UQIugyIXeBTduabrOh0eZSU5"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Axe-06",
    description:     "Berserker axe — jagged edge, dark iron, blood-stained texture. OBJ + FBX, 4K PBR. High-detail close-up geometry for first-person game views.",
    price:           899,
    category:        "weapon" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1DcmVwUgfOzvl8wzJJOq-YP7pR_8ZXZ4u"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1DcmVwUgfOzvl8wzJJOq-YP7pR_8ZXZ4u"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Axe-07",
    description:     "Twin axe set — matched pair with worn leather grip wrapping and chain link connector. OBJ + FBX, 4K PBR. Designed for dual-wield combat builds.",
    price:           899,
    category:        "weapon" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1k9AhDcIY-Em7Wyl5fd2i79DomElK1DnM"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1k9AhDcIY-Em7Wyl5fd2i79DomElK1DnM"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Axe-08",
    description:     "Legendary axe — particle-effect blade with ember and smoke trails on swing. OBJ + FBX, 4K PBR. Premium detail for final boss and legendary loot drops.",
    price:           1200,
    category:        "weapon" as const,
    packageTier:     "standard" as const,
    isLatest:        true,
    isActive:        true,
    previewVideoUrl: gd("1tqcYpL3wqMpomBiXOo_N6yDwspdEgmWu"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1tqcYpL3wqMpomBiXOo_N6yDwspdEgmWu"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Hammer-01",
    description:     "War hammer with flanged iron head and worn oak haft. OBJ + FBX, 4K PBR. No rig. Solid choice for paladin, blacksmith, and siege roles.",
    price:           699,
    category:        "weapon" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1rOZz4JdPpbII8L68TkmPxCNrKhC0Bnax"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1rOZz4JdPpbII8L68TkmPxCNrKhC0Bnax"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Hammer-02",
    description:     "Thunder hammer — electrified head with crackling lightning effect on impact. OBJ + FBX, 4K PBR. Premium detail for divine and storm-class builds.",
    price:           999,
    category:        "weapon" as const,
    packageTier:     "standard" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1vzptVR7H_6LP5mt_n_8d9I1SBXggylAF"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1vzptVR7H_6LP5mt_n_8d9I1SBXggylAF"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Sword-03",
    description:     "Broad sword with double-edged blade and ornate crossguard. OBJ + FBX, 4K PBR. Clean slash geometry ideal for combo attack and parry animations.",
    price:           899,
    category:        "weapon" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("15BTm6HFoc8WUHpAbIucC1LBHY7M_bs5r"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("15BTm6HFoc8WUHpAbIucC1LBHY7M_bs5r"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },

  // ════════════════════════════════════════════════════════════════════════
  //  ARCHITECTURE — EXTERIOR
  // ════════════════════════════════════════════════════════════════════════

  {
    name:            "Exterior Design 01",
    description:     "AI-generated exterior architectural visualization. Cinematic lighting, photorealistic materials.",
    price:           499,
    category:        "exterior" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1kp23x5YBnWovDamPDT2FS00d1ID9SB0k"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Exterior Design 02",
    description:     "AI-generated exterior architectural visualization. Cinematic lighting, photorealistic materials.",
    price:           499,
    category:        "exterior" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("10CfcifgZBQMoxK2L_ANH8TJ8vUj7v26T"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Exterior Design 03",
    description:     "AI-generated exterior architectural visualization. Cinematic lighting, photorealistic materials.",
    price:           499,
    category:        "exterior" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1uK7a0BedMTfGWeZ17WxJt-YYKAJL3bZJ"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Exterior Design 04",
    description:     "AI-generated exterior architectural visualization. Cinematic lighting, photorealistic materials.",
    price:           499,
    category:        "exterior" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1On-oICTEgx81tNSRyW7DZYk3IOEDBiAT"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Exterior Design 05",
    description:     "AI-generated architectural cinematic exterior. Dramatic angles, photorealistic render.",
    price:           499,
    category:        "exterior" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1MJR8A38OCNRDxb_jRheBdRgexnAOugZf"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },

  // ════════════════════════════════════════════════════════════════════════
  //  ARCHITECTURE — INTERIOR
  // ════════════════════════════════════════════════════════════════════════

  {
    name:            "Interior Design 01",
    description:     "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.",
    price:           499,
    category:        "interior" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("16IlbksfqFgAsIUlIbSnfG1k0miktYC0d"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Interior Design 02",
    description:     "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.",
    price:           499,
    category:        "interior" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1cHTTgKBilMBXIrIGuSqB2tAb4A9WdobJ"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Interior Design 03",
    description:     "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.",
    price:           499,
    category:        "interior" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1A9sgWrWpi_Jq2NWZIH5mkh2XP491_2Ce"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Interior Design 04",
    description:     "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.",
    price:           499,
    category:        "interior" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1sr1O1HBL-q0oFZ2mfhgI3Zf3Y_AWmOzl"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Interior Design 05",
    description:     "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.",
    price:           499,
    category:        "interior" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1wQtULgqst4SX2imqwdEhnqYRgzcPWJiu"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Interior Design 06",
    description:     "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.",
    price:           499,
    category:        "interior" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1iqOFR1-0gO4v-Wk7PzBKZ2TsSeL0qoOW"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
  {
    name:            "Interior Design 07",
    description:     "AI-generated cinematic interior visualization. Moody ambient lighting, photorealistic surfaces.",
    price:           499,
    category:        "interior" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1p34uCYAykKSH9c5fHXh1PuRn_S5XS3sG"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },

  // ════════════════════════════════════════════════════════════════════════
  //  TIMELAPSE
  // ════════════════════════════════════════════════════════════════════════

  {
    name:            "House Build Timelapse 01",
    description:     "Full AI-generated house construction timelapse — exterior to interior reveal. Cinematic camera work, photorealistic render throughout.",
    price:           799,
    category:        "interior" as const,
    packageTier:     "mesh_only" as const,
    isLatest:        false,
    isActive:        true,
    previewVideoUrl: gd("1-V_JEJtAQvcl6FuldAxpFUFCUV9qwo5Q"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
    fileKeyObj:      null,
    fileKeyFbx:      null,
    fileKeyGlb:      null,
    animIdleUrl:     null,
    animWalkUrl:     null,
    animRunUrl:      null,
    animAttackOneUrl: null,
    animAttackTwoUrl: null,
    animHitUrl:      null,
  },
];

async function main() {
  console.log(`Seeding ${products.length} products...`);

  for (const p of products) {
    const seedId = `seed-${p.name.toLowerCase().replace(/\s+/g, "-")}`;
    await prisma.product.upsert({
      where:  { id: seedId },
      update: p,
      create: { id: seedId, ...p },
    });
    console.log(`✓ ${p.name}  ₱${p.price}  [${p.packageTier}]${p.isLatest ? "  ★ Latest" : ""}`);
  }

  console.log("\nDone. All products seeded.");
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());