// seedProducts.ts — Seeds the Product table with all GDrive assets.
// Run: npx ts-node prisma/seedProducts.ts

import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

// Helper: constructs a Google Drive direct view URL from a file ID.
function gd(id: string) {
  return `https://drive.google.com/file/d/${id}/view?usp=drivesdk`;
}

const products = [

  // ── CHARACTERS ──────────────────────────────────────────────────────────

  {
    name: "Orc-01",
    description: "Low-poly orc character with idle and attack animations.",
    price: 299,
    category: "character" as const,
    previewVideoUrl: gd("1ApEQgnNAza_uRL9NRRPtCMOurPqKj1VP"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1ApEQgnNAza_uRL9NRRPtCMOurPqKj1VP"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Orc-02",
    description: "Heavy orc warrior with full animation set.",
    price: 299,
    category: "character" as const,
    previewVideoUrl: gd("1SaHl7fGvD2uoy34clB1p2UWT-knWENwl"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1SaHl7fGvD2uoy34clB1p2UWT-knWENwl"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Orc-03",
    description: "Tribal orc character with detailed textures.",
    price: 299,
    category: "character" as const,
    previewVideoUrl: gd("1L_mshqNnDK3rfTHrcds3yApBiY-Wt55i"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1L_mshqNnDK3rfTHrcds3yApBiY-Wt55i"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Orc-04",
    description: "Battle-scarred orc with dynamic movement animation.",
    price: 349,
    category: "character" as const,
    previewVideoUrl: gd("1cx2sETIft3K7R8NnNPumoLet1pW5It0a"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1cx2sETIft3K7R8NnNPumoLet1pW5It0a"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Orc-05",
    description: "Shaman orc character with ceremonial armor.",
    price: 349,
    category: "character" as const,
    previewVideoUrl: gd("1-n33tw86ViaKB6xzM0UuCrgF45JVc63-"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1-n33tw86ViaKB6xzM0UuCrgF45JVc63-"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Orc-06",
    description: "Armored orc guard with shield and weapon animations.",
    price: 349,
    category: "character" as const,
    previewVideoUrl: gd("1XVymFPXK8aQa-Ud7DwpkaQ6g3BrGiLjH"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1XVymFPXK8aQa-Ud7DwpkaQ6g3BrGiLjH"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Orc-07",
    description: "Berserker orc with rage-mode animation.",
    price: 349,
    category: "character" as const,
    previewVideoUrl: gd("16-RCaA3WjQjMf1GT0Ad2JrjAhR-U_FyH"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("16-RCaA3WjQjMf1GT0Ad2JrjAhR-U_FyH"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Orc-08",
    description: "Elite orc commander with full battle animation set.",
    price: 399,
    category: "character" as const,
    previewVideoUrl: gd("1Wjgt2RcRkUrbxEMnLQWWdiUdQ3OHwpx3"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1Wjgt2RcRkUrbxEMnLQWWdiUdQ3OHwpx3"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Orc-09",
    description: "Scout orc with stealth and sprint animations.",
    price: 399,
    category: "character" as const,
    previewVideoUrl: gd("1JB-kYyq0XMrPe0pgrh5L2S-nGmK-wvXE"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1JB-kYyq0XMrPe0pgrh5L2S-nGmK-wvXE"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Orc-10",
    description: "Warchief orc with elaborate armor and battle cry animation.",
    price: 399,
    category: "character" as const,
    previewVideoUrl: gd("1q3rW69QWjYEK5T53rRTpTFlR7X9ZERRe"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1q3rW69QWjYEK5T53rRTpTFlR7X9ZERRe"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Orc-11",
    description: "Siege orc with heavy armor and slam animation.",
    price: 399,
    category: "character" as const,
    previewVideoUrl: gd("1CTk71XmBB9yNz9Osbfd-YHg9mrsgmZkf"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1CTk71XmBB9yNz9Osbfd-YHg9mrsgmZkf"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Orc-12",
    description: "Dark shaman orc with glowing rune details and cast animation.",
    price: 449,
    category: "character" as const,
    previewVideoUrl: gd("1ZPSoWhJc0ukVny9sCKp0-ytzTsz0aL50"),
    facePngUrl:      gd("1ai8U8_LmCzgaZHITTUJ9J6FEUjUdwE61"),
    threeDUrl:       null,
    actionOneUrl:    gd("1ZPSoWhJc0ukVny9sCKp0-ytzTsz0aL50"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Orc-13",
    description: "Legendary orc hero with full cinematic animation.",
    price: 449,
    category: "character" as const,
    previewVideoUrl: gd("1W1eHcST6_noKH3VCygvpKz-JFZkCF6Su"),
    facePngUrl:      gd("1uRu_SW840F9l8UqHlLYh85d60z91qQWM"),
    threeDUrl:       null,
    actionOneUrl:    gd("1W1eHcST6_noKH3VCygvpKz-JFZkCF6Su"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },

  // ── WEAPONS ─────────────────────────────────────────────────────────────

  {
    name: "Axe-01",
    description: "Standard battle axe with swing animation.",
    price: 199,
    category: "weapon" as const,
    previewVideoUrl: gd("1NrTbKznn-3pcIC9q-BqBa2lUfMUsGKa8"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1NrTbKznn-3pcIC9q-BqBa2lUfMUsGKa8"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Axe-02",
    description: "Dual-blade axe with combo animation set.",
    price: 199,
    category: "weapon" as const,
    previewVideoUrl: gd("1db1EOrzdG2phPiaJ8DJV9Tz1-bfYwB67"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1db1EOrzdG2phPiaJ8DJV9Tz1-bfYwB67"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Axe-03",
    description: "Ornate ceremonial axe with detailed engravings.",
    price: 229,
    category: "weapon" as const,
    previewVideoUrl: gd("1ZPhiN56sAU9EQIlrrTPY3OSDBhijtHld"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1ZPhiN56sAU9EQIlrrTPY3OSDBhijtHld"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Axe-04",
    description: "Heavy war axe with overhead slam animation.",
    price: 229,
    category: "weapon" as const,
    previewVideoUrl: gd("1jjU-r5EawMDjzhbJueiadCMjkcCZrHtr"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1jjU-r5EawMDjzhbJueiadCMjkcCZrHtr"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Axe-05",
    description: "Rune-carved axe with glowing effect animation.",
    price: 249,
    category: "weapon" as const,
    previewVideoUrl: gd("1vl3KhBI_UQIugyIXeBTduabrOh0eZSU5"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1vl3KhBI_UQIugyIXeBTduabrOh0eZSU5"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Axe-06",
    description: "Berserker axe with blood trail animation.",
    price: 249,
    category: "weapon" as const,
    previewVideoUrl: gd("1DcmVwUgfOzvl8wzJJOq-YP7pR_8ZXZ4u"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1DcmVwUgfOzvl8wzJJOq-YP7pR_8ZXZ4u"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Axe-07",
    description: "Twin axe set with dual-wield animation.",
    price: 249,
    category: "weapon" as const,
    previewVideoUrl: gd("1k9AhDcIY-Em7Wyl5fd2i79DomElK1DnM"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1k9AhDcIY-Em7Wyl5fd2i79DomElK1DnM"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Axe-08",
    description: "Legendary axe with particle effect on swing.",
    price: 299,
    category: "weapon" as const,
    previewVideoUrl: gd("1tqcYpL3wqMpomBiXOo_N6yDwspdEgmWu"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1tqcYpL3wqMpomBiXOo_N6yDwspdEgmWu"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Hammer-01",
    description: "War hammer with ground smash animation.",
    price: 199,
    category: "weapon" as const,
    previewVideoUrl: gd("1rOZz4JdPpbII8L68TkmPxCNrKhC0Bnax"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1rOZz4JdPpbII8L68TkmPxCNrKhC0Bnax"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Hammer-02",
    description: "Thunder hammer with lightning strike animation.",
    price: 229,
    category: "weapon" as const,
    previewVideoUrl: gd("1vzptVR7H_6LP5mt_n_8d9I1SBXggylAF"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("1vzptVR7H_6LP5mt_n_8d9I1SBXggylAF"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Sword-03",
    description: "Broad sword with slash and parry animations.",
    price: 229,
    category: "weapon" as const,
    previewVideoUrl: gd("15BTm6HFoc8WUHpAbIucC1LBHY7M_bs5r"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    gd("15BTm6HFoc8WUHpAbIucC1LBHY7M_bs5r"),
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },

  // ── EXTERIOR ─────────────────────────────────────────────────────────────

  {
    name: "Exterior Design 01",
    description: "AI-generated exterior architectural visualization.",
    price: 499,
    category: "exterior" as const,
    previewVideoUrl: gd("1kp23x5YBnWovDamPDT2FS00d1ID9SB0k"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Exterior Design 02",
    description: "AI-generated exterior architectural visualization.",
    price: 499,
    category: "exterior" as const,
    previewVideoUrl: gd("10CfcifgZBQMoxK2L_ANH8TJ8vUj7v26T"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Exterior Design 03",
    description: "AI-generated exterior architectural visualization.",
    price: 499,
    category: "exterior" as const,
    previewVideoUrl: gd("1uK7a0BedMTfGWeZ17WxJt-YYKAJL3bZJ"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Exterior Design 04",
    description: "AI-generated exterior architectural visualization.",
    price: 499,
    category: "exterior" as const,
    previewVideoUrl: gd("1On-oICTEgx81tNSRyW7DZYk3IOEDBiAT"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Exterior Design 05",
    description: "AI-generated architectural cinematic exterior.",
    price: 499,
    category: "exterior" as const,
    previewVideoUrl: gd("1MJR8A38OCNRDxb_jRheBdRgexnAOugZf"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },

  // ── INTERIOR ─────────────────────────────────────────────────────────────

  {
    name: "Interior Design 01",
    description: "AI-generated cinematic interior architectural visualization.",
    price: 499,
    category: "interior" as const,
    previewVideoUrl: gd("16IlbksfqFgAsIUlIbSnfG1k0miktYC0d"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Interior Design 02",
    description: "AI-generated cinematic interior architectural visualization.",
    price: 499,
    category: "interior" as const,
    previewVideoUrl: gd("1cHTTgKBilMBXIrIGuSqB2tAb4A9WdobJ"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Interior Design 03",
    description: "AI-generated cinematic interior architectural visualization.",
    price: 499,
    category: "interior" as const,
    previewVideoUrl: gd("1A9sgWrWpi_Jq2NWZIH5mkh2XP491_2Ce"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Interior Design 04",
    description: "AI-generated cinematic interior architectural visualization.",
    price: 499,
    category: "interior" as const,
    previewVideoUrl: gd("1sr1O1HBL-q0oFZ2mfhgI3Zf3Y_AWmOzl"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Interior Design 05",
    description: "AI-generated cinematic interior architectural visualization.",
    price: 499,
    category: "interior" as const,
    previewVideoUrl: gd("1wQtULgqst4SX2imqwdEhnqYRgzcPWJiu"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Interior Design 06",
    description: "AI-generated cinematic interior architectural visualization.",
    price: 499,
    category: "interior" as const,
    previewVideoUrl: gd("1iqOFR1-0gO4v-Wk7PzBKZ2TsSeL0qoOW"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
  {
    name: "Interior Design 07",
    description: "AI-generated cinematic interior architectural visualization.",
    price: 499,
    category: "interior" as const,
    previewVideoUrl: gd("1p34uCYAykKSH9c5fHXh1PuRn_S5XS3sG"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },

  // ── TIMELAPSE (Interior + Exterior combined) ──────────────────────────────

  {
    name: "House Build Timelapse 01",
    description: "Full AI-generated house construction timelapse — interior and exterior.",
    price: 799,
    category: "interior" as const,
    previewVideoUrl: gd("1-V_JEJtAQvcl6FuldAxpFUFCUV9qwo5Q"),
    facePngUrl:      null,
    threeDUrl:       null,
    actionOneUrl:    null,
    actionTwoUrl:    null,
    actionThreeUrl:  null,
  },
];

async function main() {
  console.log(`Seeding ${products.length} products...`);

  for (const p of products) {
    await prisma.product.upsert({
      where:  { id: `seed-${p.name.toLowerCase().replace(/\s+/g, "-")}` },
      update: p,
      create: { id: `seed-${p.name.toLowerCase().replace(/\s+/g, "-")}`, ...p },
    });
    console.log(`✓ ${p.name}`);
  }

  console.log("Done. All products seeded.");
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());