// seedSystems.ts — seeds System and SystemAddon tables.
// Run: npx ts-node prisma/seedSystems.ts
// or add to prisma/seed.ts if you have one.

import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const systemsData = [
  {
    tag: "HR", title: "Payroll & HR System", basePrice: 33000, accent: "#67e8f9",
    timeline: "8–11 weeks", deploy: "Web / IIS",
    description: "BIR-compliant payroll and HR management in one place.",
    features: ["BIR-compliant payroll","SSS / PhilHealth / Pag-IBIG","Payslip generation","Employee records","DTR management"],
    addons: [
      { addonKey:"hr1",  label:"Automated Payroll Processing",       price:5000,  category:"Payroll",      description:"Auto-compute salary based on attendance, deductions, and allowances every cutoff." },
      { addonKey:"hr2",  label:"Overtime Computation",               price:2800,  category:"Payroll",      description:"Auto-calculate OT pay based on hours rendered and applicable multipliers." },
      { addonKey:"hr3",  label:"Night Differential Computation",     price:2500,  category:"Payroll",      description:"ND pay computation for hours worked between 10PM–6AM per DOLE guidelines." },
      { addonKey:"hr4",  label:"Holiday Pay Computation",            price:2800,  category:"Payroll",      description:"Automatic holiday pay rates — regular, special, and double holiday." },
      { addonKey:"hr5",  label:"13th Month Pay Automation",          price:2800,  category:"Payroll",      description:"Auto-compute 13th month pay based on basic pay and months worked." },
      { addonKey:"hr6",  label:"Incentive & Bonus Management",       price:3500,  category:"Payroll",      description:"Performance bonuses, commissions, and allowances added to payroll processing." },
      { addonKey:"hr7",  label:"Final Pay Computation",              price:3500,  category:"Payroll",      description:"Employee clearance payroll — last pay, unused leaves, and deduction settlement." },
      { addonKey:"hr8",  label:"Payroll Approval Workflow",          price:4000,  category:"Payroll",      description:"Multi-level payroll approval before disbursement — HR → Finance → GM." },
      { addonKey:"hr9",  label:"Multi-Branch Payroll",               price:5500,  category:"Payroll",      description:"Consolidated payroll management across multiple branches or departments." },
      { addonKey:"hr10", label:"Payslip Generator (PDF + Email)",    price:2500,  category:"Payroll",      description:"Auto-generate and email payslips to employees every cutoff." },
      { addonKey:"hr11", label:"BIR Tax Computation & Forms",        price:6000,  category:"Compliance",   description:"Auto-compute withholding tax and generate BIR forms 2316, 1601C, Alphalist." },
      { addonKey:"hr12", label:"SSS Contribution Automation",        price:3500,  category:"Compliance",   description:"Auto-compute SSS contributions per current contribution schedule." },
      { addonKey:"hr13", label:"PhilHealth Integration",             price:3500,  category:"Compliance",   description:"Auto-compute PhilHealth monthly premiums based on salary brackets." },
      { addonKey:"hr14", label:"Pag-IBIG (HDMF) Contribution",      price:3500,  category:"Compliance",   description:"Auto-compute Pag-IBIG contributions and generate remittance reports." },
      { addonKey:"hr15", label:"Government Remittance Reports",      price:4000,  category:"Compliance",   description:"Printable SSS R3, PhilHealth RF-1, and HDMF remittance schedules per cutoff." },
      { addonKey:"hr16", label:"Tax Table Auto Updates",             price:2500,  category:"Compliance",   description:"Tax bracket auto-updates when BIR releases new TRAIN Law adjustments." },
      { addonKey:"hr17", label:"Compliance Audit Reports",           price:4500,  category:"Compliance",   description:"HR compliance monitoring with audit trail and government submission history." },
      { addonKey:"hr18", label:"Biometric Integration",              price:8000,  category:"Attendance",   description:"Connect fingerprint biometric devices for automatic time-in/time-out logging." },
      { addonKey:"hr19", label:"RFID Attendance",                    price:6000,  category:"Attendance",   description:"RFID tap-in attendance with card assignment and access log reporting." },
      { addonKey:"hr20", label:"GPS Attendance Tracking",            price:5000,  category:"Attendance",   description:"Location-based attendance for field employees with map view." },
      { addonKey:"hr21", label:"Mobile Time Tracking",               price:3500,  category:"Attendance",   description:"Employees clock in/out via mobile app with selfie verification." },
      { addonKey:"hr22", label:"Shift Scheduling",                   price:4500,  category:"Attendance",   description:"Build and assign shift schedules with conflict detection and rotation support." },
      { addonKey:"hr23", label:"Break Time Monitoring",              price:2500,  category:"Attendance",   description:"Track lunch and break durations with automatic undertime computation." },
      { addonKey:"hr24", label:"Geo-Fencing Attendance",             price:5000,  category:"Attendance",   description:"Restrict clock-in to a defined GPS radius — prevents buddy punching." },
      { addonKey:"hr25", label:"Overtime Approval Workflow",         price:2800,  category:"Attendance",   description:"Employees file OT requests, supervisors approve before OT pay is computed." },
      { addonKey:"hr26", label:"Attendance Correction Requests",     price:2500,  category:"Attendance",   description:"Employees file missed punch corrections with supporting reason and approver." },
      { addonKey:"hr27", label:"Employee Self-Service Portal",       price:5500,  category:"HR Mgmt",      description:"Employees view payslips, file leaves, check attendance, and update info online." },
      { addonKey:"hr28", label:"Leave Management",                   price:3000,  category:"HR Mgmt",      description:"Track vacation, sick, emergency leave balances with approval workflow." },
      { addonKey:"hr29", label:"Employee Onboarding",                price:5000,  category:"HR Mgmt",      description:"Digital onboarding checklist — contracts, requirements, and orientation flow." },
      { addonKey:"hr30", label:"Exit Management",                    price:4000,  category:"HR Mgmt",      description:"Resignation and clearance workflow with final pay computation trigger." },
      { addonKey:"hr31", label:"HR Document Management",             price:5000,  category:"HR Mgmt",      description:"Digital 201 file — store contracts, IDs, certifications, and memos." },
      { addonKey:"hr32", label:"Organizational Chart",               price:2800,  category:"HR Mgmt",      description:"Visual company hierarchy with department and reporting line management." },
      { addonKey:"hr33", label:"Employee Disciplinary Tracking",     price:2800,  category:"HR Mgmt",      description:"Log violations, notices to explain, and corrective actions per employee." },
      { addonKey:"hr34", label:"Digital Forms & Requests",           price:3500,  category:"HR Mgmt",      description:"Online HR forms — COE requests, loan applications, and change of info." },
      { addonKey:"hr35", label:"Applicant Tracking System (ATS)",    price:7000,  category:"Recruitment",  description:"End-to-end recruitment pipeline — job posting, screening, interviews, and hiring." },
      { addonKey:"hr36", label:"Resume Parser",                      price:5000,  category:"Recruitment",  description:"Auto-extract candidate info from uploaded CVs into structured profile fields." },
      { addonKey:"hr37", label:"Interview Scheduling",               price:3500,  category:"Recruitment",  description:"Schedule and manage interview slots with email notifications to candidates." },
      { addonKey:"hr38", label:"AI Resume Screening",                price:9000,  category:"Recruitment",  description:"AI ranks and filters applicants based on job requirements and keywords." },
      { addonKey:"hr39", label:"KPI Performance Tracking",           price:5000,  category:"Performance",  description:"Set, monitor, and score employee KPIs per department or role." },
      { addonKey:"hr40", label:"Performance Evaluation System",      price:5000,  category:"Performance",  description:"360-degree appraisal forms with self-assessment and manager scoring." },
      { addonKey:"hr41", label:"Learning Management System (LMS)",   price:7000,  category:"Performance",  description:"Online training portal with course assignments, quizzes, and completion tracking." },
      { addonKey:"hr42", label:"Certification Tracking",             price:2500,  category:"Performance",  description:"Track employee certifications, expiry dates, and renewal reminders." },
      { addonKey:"hr43", label:"Payroll Dashboard",                  price:4500,  category:"Dashboard",    description:"Live payroll KPIs — total payroll cost, headcount, deductions, and net pay." },
      { addonKey:"hr44", label:"Attendance & Leave Reports",         price:3000,  category:"Data Analysis", description:"Absence rates, late logs, leave balance summaries, and trend charts." },
      { addonKey:"hr45", label:"Employee Turnover Reports",          price:3500,  category:"Data Analysis", description:"Attrition rate by department, tenure band, and resignation reason analysis." },
      { addonKey:"hr46", label:"Salary Forecasting",                 price:6000,  category:"Data Analysis", description:"Predict payroll budget for next quarter based on headcount and salary trends." },
      { addonKey:"hr47", label:"Automated Scheduled Reports",        price:2500,  category:"Data Analysis", description:"Auto-generate and email payroll, attendance, and HR reports on a schedule." },
      { addonKey:"hr48", label:"Payroll Journal Entries",            price:4500,  category:"Accounting",   description:"Auto-post payroll to accounting — debit salaries, credit payables and tax." },
      { addonKey:"hr49", label:"Cost Center Allocation",             price:5000,  category:"Accounting",   description:"Allocate payroll costs to departments, projects, or cost centers." },
      { addonKey:"hr50", label:"QuickBooks / Xero Sync",             price:5000,  category:"Accounting",   description:"Two-way payroll sync with QuickBooks or Xero accounting software." },
      { addonKey:"hr51", label:"AI Payroll Assistant",               price:7000,  category:"AI",           description:"AI flags anomalies, suggests corrections, and automates routine payroll tasks." },
      { addonKey:"hr52", label:"AI Attendance Fraud Detection",      price:9000,  category:"AI",           description:"Detect buddy punching, GPS spoofing, and pattern-based attendance fraud." },
      { addonKey:"hr53", label:"AI Employee Performance Prediction", price:9000,  category:"AI",           description:"AI scores flight risk, performance trajectory, and promotion readiness." },
      { addonKey:"hr54", label:"Automated Workflow Engine",          price:7500,  category:"AI",           description:"Auto-trigger onboarding, reminders, escalations, and approvals based on rules." },
    ],
  },
  {
    tag: "Construction", title: "Construction Project System", basePrice: 45000, accent: "#7eb8d4",
    timeline: "10–12 weeks", deploy: "Web / IIS",
    description: "Full project oversight engineered for construction enterprises.",
    features: ["Project timelines","Material logistics","Contractor management","Budget tracking","Gantt chart"],
    addons: [
      { addonKey:"co1",  label:"Project Management",           price:5000,  category:"Core Modules",    description:"Tasks, milestones, and workflows for full project lifecycle management." },
      { addonKey:"co2",  label:"Document Management",          price:3500,  category:"Core Modules",    description:"Centralized storage for drawings, contracts, and project files with version control." },
      { addonKey:"co3",  label:"Client Portal",                price:4500,  category:"Core Modules",    description:"Customer-facing dashboard for project updates, approvals, and progress visibility." },
      { addonKey:"co4",  label:"Contractor Portal",            price:5000,  category:"Core Modules",    description:"Subcontractor access for task updates, document sharing, and billing submissions." },
      { addonKey:"co5",  label:"Daily Logs",                   price:2500,  category:"Core Modules",    description:"Site activity tracking — manpower, weather, equipment, and work completed each day." },
      { addonKey:"co6",  label:"Punch List Management",        price:3000,  category:"Core Modules",    description:"Defect and snagging tracker with photo evidence, assignee, and close-out workflow." },
      { addonKey:"co7",  label:"Change Order Management",      price:5000,  category:"Core Modules",    description:"Manage variation orders with client approval workflow, cost impact, and schedule update." },
      { addonKey:"co8",  label:"RFI Management",               price:4500,  category:"Core Modules",    description:"Request for Information workflows with routing, deadlines, and response tracking." },
      { addonKey:"co9",  label:"Submittal Tracking",           price:5000,  category:"Core Modules",    description:"Material and shop drawing approvals with revision history and approval status." },
      { addonKey:"co10", label:"Quality Control System",       price:7500,  category:"Core Modules",    description:"QA/QC inspection forms, checklist management, and non-conformance reporting." },
      { addonKey:"co11", label:"Incident Reporting",           price:3000,  category:"Core Modules",    description:"Safety incident and accident logging with investigation workflow and corrective actions." },
      { addonKey:"co12", label:"Digital Takeoff",              price:5000,  category:"Estimation",      description:"Measure plans digitally from uploaded drawings — area, length, count, and volume." },
      { addonKey:"co13", label:"AI Cost Estimation",           price:9000,  category:"Estimation",      description:"AI-generated cost estimates based on project type, scope, and historical data." },
      { addonKey:"co14", label:"Quantity Surveying Module",    price:8000,  category:"Estimation",      description:"Bill of quantities computation and material takeoff with cost buildup per trade." },
      { addonKey:"co15", label:"Material Cost Database",       price:5000,  category:"Estimation",      description:"Real-time pricing database for construction materials with supplier comparison." },
      { addonKey:"co16", label:"Labor Cost Calculator",        price:3500,  category:"Estimation",      description:"Wage and manpower estimation with daily, weekly, and project-based labor costing." },
      { addonKey:"co17", label:"Equipment Cost Estimator",     price:3000,  category:"Estimation",      description:"Equipment usage costing with rental rates and ownership cost computation." },
      { addonKey:"co18", label:"Bid Management",               price:7000,  category:"Estimation",      description:"Tender submission management with bid comparison, scoring, and award tracking." },
      { addonKey:"co19", label:"Proposal Generator",           price:4500,  category:"Estimation",      description:"Auto-generate professional client proposals from estimate data with branding." },
      { addonKey:"co20", label:"Auto BOQ Generator",           price:8000,  category:"Estimation",      description:"Automated Bill of Quantities generation from project scope and takeoff data." },
      { addonKey:"co21", label:"AI Bid Optimization",          price:12000, category:"Estimation",      description:"AI suggests optimal pricing strategies to win bids while protecting margins." },
      { addonKey:"co22", label:"Gantt Chart Scheduler",        price:4500,  category:"Scheduling",      description:"Interactive timeline management with task dependencies and critical path highlighting." },
      { addonKey:"co23", label:"CPM Scheduling",               price:8000,  category:"Scheduling",      description:"Critical Path Method scheduling with float analysis and schedule optimization." },
      { addonKey:"co24", label:"Resource Scheduling",          price:5500,  category:"Scheduling",      description:"Labor and equipment planning with capacity calendar and conflict detection." },
      { addonKey:"co25", label:"Baseline Tracking",            price:4500,  category:"Scheduling",      description:"Compare planned vs. actual schedule with variance analysis and earned value metrics." },
      { addonKey:"co26", label:"Delay Analysis",               price:6000,  category:"Scheduling",      description:"Analyze project delays with cause classification and impact on critical path." },
      { addonKey:"co27", label:"Lookahead Planning",           price:3500,  category:"Scheduling",      description:"3–6 week rolling work plans for site supervisors with crew and material readiness." },
      { addonKey:"co28", label:"AI Schedule Forecasting",      price:12000, category:"Scheduling",      description:"Predict delays and project completion dates using AI pattern recognition." },
      { addonKey:"co29", label:"BIM Integration",              price:15000, category:"BIM",             description:"3D building model integration for clash detection, quantity extraction, and coordination." },
      { addonKey:"co30", label:"Clash Detection",              price:18000, category:"BIM",             description:"Detect and report design conflicts between MEP, structural, and architectural models." },
      { addonKey:"co31", label:"Revit Integration",            price:6000,  category:"BIM",             description:"Sync model data and quantities directly from Autodesk Revit into the project system." },
      { addonKey:"co32", label:"AutoCAD Integration",          price:5000,  category:"BIM",             description:"Import and annotate CAD drawings directly within the project platform." },
      { addonKey:"co33", label:"Drone Mapping",                price:18000, category:"BIM",             description:"Site aerial scanning and orthophoto generation from drone survey data." },
      { addonKey:"co34", label:"Procurement System",           price:6000,  category:"Procurement",     description:"Purchase management from requisition to PO to receiving with approval workflow." },
      { addonKey:"co35", label:"Vendor Portal",                price:5000,  category:"Procurement",     description:"Supplier collaboration portal for quote submission, PO acknowledgment, and invoicing." },
      { addonKey:"co36", label:"RFQ Automation",               price:4500,  category:"Procurement",     description:"Request-for-quote workflows with multi-vendor comparison and auto-award logic." },
      { addonKey:"co37", label:"Purchase Orders",              price:3500,  category:"Procurement",     description:"Generate and track material purchase orders with budget linkage and receiving confirmation." },
      { addonKey:"co38", label:"Inventory Tracking",           price:5000,  category:"Procurement",     description:"Construction material inventory with site-level tracking and consumption reporting." },
      { addonKey:"co39", label:"Equipment Rental Management",  price:5500,  category:"Procurement",     description:"Rental equipment monitoring with utilization tracking and rental cost logging." },
      { addonKey:"co40", label:"Subcontractor Management",     price:7000,  category:"Procurement",     description:"Subcontractor tracking, compliance management, and performance scoring per project." },
      { addonKey:"co41", label:"Job Costing",                  price:6000,  category:"Finance",         description:"Real-time project cost tracking against budget with WBS cost code breakdown." },
      { addonKey:"co42", label:"Budget Management",            price:5000,  category:"Finance",         description:"Budget forecasting with earned value tracking and cost-to-complete projections." },
      { addonKey:"co43", label:"Progress Billing",             price:5000,  category:"Finance",         description:"Construction invoicing tied to percentage completion with client approval workflow." },
      { addonKey:"co44", label:"Retention Tracking",           price:3500,  category:"Finance",         description:"Retainage monitoring and automatic release calculation at project milestones." },
      { addonKey:"co45", label:"Accounts Payable",             price:5500,  category:"Finance",         description:"Vendor payment workflows with three-way matching (PO, GR, invoice) and approval routing." },
      { addonKey:"co46", label:"Accounts Receivable",          price:5000,  category:"Finance",         description:"Client receivables tracking with aging reports and collection follow-up automation." },
      { addonKey:"co47", label:"Tax Management",               price:3500,  category:"Finance",         description:"VAT/EVAT calculations, BIR compliance forms, and tax certificate generation." },
      { addonKey:"co48", label:"Financial Forecasting",        price:8000,  category:"Finance",         description:"Cashflow prediction with S-curve analysis and project financial health scoring." },
      { addonKey:"co49", label:"Time Tracking",                price:3000,  category:"Workforce",       description:"Worker attendance and time logging with daily time record (DTR) generation." },
      { addonKey:"co50", label:"Crew Management",              price:4000,  category:"Workforce",       description:"Labor coordination with gang/crew assignment, headcount tracking, and shift management." },
      { addonKey:"co51", label:"GPS Attendance",               price:3500,  category:"Workforce",       description:"Geolocation-based check-in/check-out — workers can only clock in within site perimeter." },
      { addonKey:"co52", label:"Biometric Attendance",         price:9000,  category:"Workforce",       description:"Fingerprint or facial recognition attendance hardware integration for construction sites." },
      { addonKey:"co53", label:"Payroll Automation",           price:5500,  category:"Workforce",       description:"Automated salary computation with SSS/PhilHealth/Pag-IBIG deductions and payslip generation." },
      { addonKey:"co54", label:"Safety Compliance",            price:7000,  category:"Workforce",       description:"DOLE/OSHA compliance documentation, toolbox talk logs, and safety officer dashboards." },
      { addonKey:"co55", label:"Certification Tracking",       price:3500,  category:"Workforce",       description:"Track worker licenses, TESDA certificates, and trade qualifications with expiry alerts." },
      { addonKey:"co56", label:"Mobile Site App",              price:6000,  category:"Field & Mobile",  description:"Android/iOS app for site engineers — daily logs, progress photos, and approvals on-site." },
      { addonKey:"co57", label:"Offline Mode",                 price:4500,  category:"Field & Mobile",  description:"Full offline operation for remote sites with automatic sync when connectivity returns." },
      { addonKey:"co58", label:"Site Photo Management",        price:3000,  category:"Field & Mobile",  description:"Progress photo tracking with timestamps, geo-tags, and automatic album per work area." },
      { addonKey:"co59", label:"Voice Notes",                  price:2500,  category:"Field & Mobile",  description:"Record and attach voice memos to tasks, issues, and daily log entries from mobile." },
      { addonKey:"co60", label:"Mobile Inspections",           price:5000,  category:"Field & Mobile",  description:"Mobile QA/QC inspection forms with photo capture, digital signature, and auto-report." },
      { addonKey:"co61", label:"AI Cost Forecasting",          price:12000, category:"AI & Automation", description:"Predict future project costs using AI trained on historical construction cost data." },
      { addonKey:"co62", label:"AI Risk Detection",            price:10000, category:"AI & Automation", description:"Detect project risks early using schedule, cost, and site activity pattern analysis." },
      { addonKey:"co63", label:"AI Safety Monitoring",         price:18000, category:"AI & Automation", description:"PPE detection and hazard identification from site cameras using computer vision." },
      { addonKey:"co64", label:"AI Document Analysis",         price:8000,  category:"AI & Automation", description:"Analyze contracts, RFIs, and submittals using AI to flag risks and extract key data." },
      { addonKey:"co65", label:"ChatGPT-Style Assistant",      price:6000,  category:"AI & Automation", description:"AI project assistant for answering questions about your project data and documents." },
      { addonKey:"co66", label:"API Access",                   price:8000,  category:"Enterprise",      description:"Full REST API with key authentication for integrating with ERP, BIM, or custom platforms." },
      { addonKey:"co67", label:"QuickBooks Integration",       price:3500,  category:"Enterprise",      description:"Sync project financials, invoices, and payments with QuickBooks accounting." },
      { addonKey:"co68", label:"Power BI Integration",         price:5000,  category:"Enterprise",      description:"Connect project data to Power BI for custom executive analytics dashboards." },
      { addonKey:"co69", label:"Single Sign-On (SSO)",         price:5000,  category:"Enterprise",      description:"Enterprise SSO login via Google Workspace, Azure AD, or Okta for secure access." },
      { addonKey:"co70", label:"White Label Branding",         price:8000,  category:"Enterprise",      description:"Custom logo, company name, and color scheme throughout the entire platform." },
      { addonKey:"co71", label:"Permit Tracking",              price:3500,  category:"Compliance",      description:"Track building permits, LGU clearances, and compliance documents with expiry alerts." },
      { addonKey:"co72", label:"Inspection Scheduling",        price:3000,  category:"Compliance",      description:"Schedule and track government and third-party inspections with checklist management." },
      { addonKey:"co73", label:"Environmental Compliance",     price:9000,  category:"Compliance",      description:"ESG and DENR environmental monitoring, waste management logging, and compliance reports." },
      { addonKey:"co74", label:"OSHA Compliance",              price:8000,  category:"Compliance",      description:"OSHA/DOLE safety documentation, incident log forms, and safety officer compliance reports." },
      { addonKey:"co75", label:"Audit Logs",                   price:2500,  category:"Compliance",      description:"Full activity audit trail — who did what, when, and from which device across all modules." },
      { addonKey:"co76", label:"Lead Management",              price:4500,  category:"CRM",             description:"Sales pipeline for construction prospects with lead scoring and follow-up scheduling." },
      { addonKey:"co77", label:"Bid Tracking CRM",             price:5000,  category:"CRM",             description:"Tender opportunity tracking from inquiry to bid submission and project award." },
      { addonKey:"co78", label:"Client Messaging Portal",      price:4000,  category:"CRM",             description:"Centralized client communication with message history, file sharing, and read receipts." },
      { addonKey:"co79", label:"Sales Forecasting",            price:5000,  category:"CRM",             description:"Revenue projection from active bids and pipeline with win-rate probability scoring." },
      { addonKey:"co80", label:"Fleet Tracking",               price:9000,  category:"Equipment",       description:"GPS equipment location monitoring and utilization tracking across all active sites." },
      { addonKey:"co81", label:"Fuel Monitoring",              price:6000,  category:"Equipment",       description:"Fuel consumption analytics per machine with refueling log and theft detection alerts." },
      { addonKey:"co82", label:"Equipment Maintenance",        price:5000,  category:"Equipment",       description:"Preventive maintenance scheduling with service history, parts inventory, and downtime log." },
      { addonKey:"co83", label:"Equipment Utilization Reports",price:4500,  category:"Equipment",       description:"Usage optimization reports showing idle time, over-utilization, and cost per hour." },
      { addonKey:"co84", label:"Smart Sensors",                price:15000, category:"IoT",             description:"Site monitoring sensors for temperature, humidity, vibration, and structural health." },
      { addonKey:"co85", label:"Worker Wearables",             price:12000, category:"IoT",             description:"Smart helmet or vest integration with GPS location and real-time safety alerts." },
      { addonKey:"co86", label:"Smart Access Control",         price:12000, category:"IoT",             description:"Gate entry automation with badge, QR, or biometric access and visitor management." },
      { addonKey:"co87", label:"Environmental Sensors",        price:9000,  category:"IoT",             description:"Dust, noise, and air quality monitoring with automated alerts when limits are exceeded." },
    ],
  },
  {
    tag: "Education", title: "School & Enrollment System", basePrice: 37500, accent: "#86efac",
    timeline: "9–12 weeks", deploy: "Web / IIS",
    description: "Complete enrollment and grade management for schools.",
    features: ["Student enrollment","Grade management","Tuition tracking","Parent portal","Section management"],
    addons: [
      { addonKey:"ed1",  label:"Grade Management & GWA Computation", price:4000, category:"Academic",      description:"" },
      { addonKey:"ed2",  label:"Tuition & Fee Payment Tracking",      price:3500, category:"Finance",       description:"" },
      { addonKey:"ed3",  label:"Parent Portal",                       price:5000, category:"Portal",        description:"" },
      { addonKey:"ed4",  label:"Report Card Generation",              price:3000, category:"Academic",      description:"" },
      { addonKey:"ed5",  label:"Daily Attendance Monitoring",         price:2500, category:"Operations",    description:"" },
      { addonKey:"ed6",  label:"Enrollment Analytics Dashboard",      price:4000, category:"Dashboard",     description:"" },
      { addonKey:"ed7",  label:"Subject & Teacher Assignment",        price:2500, category:"Academic",      description:"" },
      { addonKey:"ed8",  label:"Tuition Invoice Generation",          price:2500, category:"Invoices",      description:"" },
      { addonKey:"ed9",  label:"Student Performance Reports",         price:3500, category:"Data Analysis",  description:"" },
      { addonKey:"ed10", label:"SMS/Email Notifications",             price:3000, category:"Automation",    description:"" },
    ],
  },
  {
    tag: "E-commerce", title: "POS + Mini E-commerce", basePrice: 42000, accent: "#f9a8d4",
    timeline: "9–11 weeks", deploy: "Web",
    description: "Sell in-store and online from one dashboard.",
    features: ["In-store POS","Online storefront","Synced inventory","PayMongo payments","Order tracking"],
    addons: [
      { addonKey:"pos1",  label:"Multi-Branch POS",               price:6000,  category:"Core POS",     description:"Manage multiple store locations from one dashboard with per-branch reporting." },
      { addonKey:"pos2",  label:"Multi-Cashier System",           price:3000,  category:"Core POS",     description:"Multiple cashier accounts with individual session tracking and shift reports." },
      { addonKey:"pos3",  label:"Barcode Scanning",               price:2500,  category:"Core POS",     description:"Barcode product scanning for fast checkout — USB and wireless scanner support." },
      { addonKey:"pos4",  label:"Inventory Management",           price:4500,  category:"Core POS",     description:"Real-time stock monitoring with auto-deduction per sale and restock alerts." },
      { addonKey:"pos5",  label:"Product Variants",               price:2800,  category:"Core POS",     description:"Size, color, and custom variation support with per-variant pricing and stock." },
      { addonKey:"pos6",  label:"Purchase Management",            price:3500,  category:"Core POS",     description:"Supplier purchase orders, receiving, and landed cost tracking per product." },
      { addonKey:"pos7",  label:"Stock Transfer",                 price:3000,  category:"Core POS",     description:"Inter-branch stock movement with transfer requests and approval workflow." },
      { addonKey:"pos8",  label:"Offline POS Mode",               price:5000,  category:"Core POS",     description:"Continue processing sales when internet is down — auto-syncs when reconnected." },
      { addonKey:"pos9",  label:"Loyalty Rewards System",         price:5000,  category:"Core POS",     description:"Points-based rewards — earn on every purchase, redeem on checkout." },
      { addonKey:"pos10", label:"Customer Receipt / Invoice",     price:2000,  category:"Core POS",     description:"Thermal receipt printing and PDF invoice generation per transaction." },
      { addonKey:"pos11", label:"Online Storefront",              price:7000,  category:"E-commerce",   description:"Full mini online shop — product listings, cart, and checkout flow." },
      { addonKey:"pos12", label:"Shopping Cart & Checkout",       price:4000,  category:"E-commerce",   description:"Smooth cart experience with promo code application and order confirmation." },
      { addonKey:"pos13", label:"Coupon & Promo Engine",          price:2800,  category:"E-commerce",   description:"Discount vouchers, percentage/fixed promos, and limited-time flash sales." },
      { addonKey:"pos14", label:"Product Search & Filters",       price:3500,  category:"E-commerce",   description:"Smart search with category, price range, and attribute filters." },
      { addonKey:"pos15", label:"Product Reviews & Ratings",      price:2500,  category:"E-commerce",   description:"Customer ratings and review system with moderation controls." },
      { addonKey:"pos16", label:"Wishlists",                      price:2000,  category:"E-commerce",   description:"Customers save items for later — drives return visits and conversions." },
      { addonKey:"pos17", label:"Affiliate / Referral Module",    price:6000,  category:"E-commerce",   description:"Track referral links, compute commissions, and manage affiliate payouts." },
      { addonKey:"pos18", label:"Subscription Ecommerce",         price:7000,  category:"E-commerce",   description:"Membership-based billing with recurring product delivery or access." },
      { addonKey:"pos19", label:"GCash Integration",              price:4500,  category:"Payments",     description:"Accept GCash QR and payment link transactions directly at checkout." },
      { addonKey:"pos20", label:"Maya Integration",               price:4500,  category:"Payments",     description:"Maya payments linked to POS and online checkout with auto-confirmation." },
      { addonKey:"pos21", label:"QR Payment Support",             price:3000,  category:"Payments",     description:"Universal QR code payments for in-store and online transactions." },
      { addonKey:"pos22", label:"Installment Payments",           price:5000,  category:"Payments",     description:"Split payments into scheduled installments with automatic tracking." },
      { addonKey:"pos23", label:"Auto Payment Reconciliation",    price:7500,  category:"Payments",     description:"Automatically match incoming payments to orders and close them." },
      { addonKey:"pos24", label:"Delivery Tracking",              price:5000,  category:"Delivery",     description:"Real-time delivery status updates for customers and admin." },
      { addonKey:"pos25", label:"Rider Management",               price:5500,  category:"Delivery",     description:"Assign deliveries to riders, track locations, and manage schedules." },
      { addonKey:"pos26", label:"Shipping Fee Calculator",        price:3000,  category:"Delivery",     description:"Auto-compute delivery fees based on distance, weight, or flat rates." },
      { addonKey:"pos27", label:"Courier API (LBC / J&T / NinjaVan)", price:5500, category:"Delivery", description:"Direct integration with courier APIs for booking, tracking, and label printing." },
      { addonKey:"pos28", label:"Click & Collect / Pickup",       price:3500,  category:"Delivery",     description:"Let customers order online and pick up in-store at a scheduled time." },
      { addonKey:"pos29", label:"Customer Database",              price:3000,  category:"CRM",          description:"Full customer profiles with purchase history, contact info, and loyalty points." },
      { addonKey:"pos30", label:"Gift Card System",               price:4000,  category:"CRM",          description:"Digital and physical gift cards — issue, track, and redeem at POS or online." },
      { addonKey:"pos31", label:"SMS Marketing",                  price:4000,  category:"CRM",          description:"Bulk SMS promotions, birthday greetings, and reorder reminders." },
      { addonKey:"pos32", label:"Email Marketing",                price:4000,  category:"CRM",          description:"Email campaigns for promotions, new arrivals, and win-back sequences." },
      { addonKey:"pos33", label:"Push Notifications",             price:3000,  category:"CRM",          description:"Browser and mobile push alerts for promos, order updates, and restocks." },
      { addonKey:"pos34", label:"Sales Analytics Dashboard",      price:4500,  category:"Dashboard",    description:"Live KPIs — daily revenue, top products, cashier performance, and trends." },
      { addonKey:"pos35", label:"Profit & Loss Reports",          price:4000,  category:"Data Analysis", description:"Revenue vs cost summaries per period, branch, or product category." },
      { addonKey:"pos36", label:"Product Performance Reports",    price:3000,  category:"Data Analysis", description:"Best-sellers, slow movers, return rates, and margin analysis per SKU." },
      { addonKey:"pos37", label:"Inventory Analytics",            price:3500,  category:"Data Analysis", description:"Stock movement reports, shrinkage tracking, and turnover rates." },
      { addonKey:"pos38", label:"Customer Analytics",             price:3500,  category:"Data Analysis", description:"Customer segments, purchase frequency, average spend, and churn indicators." },
      { addonKey:"pos39", label:"Employee Performance Reports",   price:3000,  category:"Data Analysis", description:"Cashier-level sales totals, transaction counts, and discount usage." },
      { addonKey:"pos40", label:"Automated Scheduled Reports",    price:2500,  category:"Data Analysis", description:"Auto-generate and email sales, inventory, and financial reports on schedule." },
      { addonKey:"pos41", label:"VAT / Tax Calculation",          price:3500,  category:"Accounting",   description:"Automatic VAT computation per transaction with BIR-compliant sales reports." },
      { addonKey:"pos42", label:"QuickBooks / Xero Sync",         price:5000,  category:"Accounting",   description:"Two-way sync of sales, inventory, and payments with accounting software." },
      { addonKey:"pos43", label:"Expense Tracking",               price:3500,  category:"Accounting",   description:"Log and categorize business expenses against branches or cost centers." },
      { addonKey:"pos44", label:"Purchase Order Automation",      price:5000,  category:"Accounting",   description:"Auto-generate POs when stock hits reorder points with supplier routing." },
      { addonKey:"pos45", label:"AI Product Recommendations",     price:7000,  category:"AI",           description:"Suggest related or frequently bought products to customers at checkout." },
      { addonKey:"pos46", label:"AI Sales Forecasting",           price:9000,  category:"AI",           description:"Predict future sales by product, branch, and season using historical data." },
      { addonKey:"pos47", label:"AI Inventory Forecasting",       price:9000,  category:"AI",           description:"Smart stock predictions to prevent overstock or stockouts before they happen." },
      { addonKey:"pos48", label:"Dynamic Pricing Engine",         price:8000,  category:"AI",           description:"Auto-adjust prices based on demand, stock levels, or competitor pricing rules." },
      { addonKey:"pos49", label:"Automated Workflow Engine",      price:7500,  category:"AI",           description:"Set rules to auto-trigger reorders, alerts, reports, and customer messages." },
    ],
  },
  {
    tag: "Warehouse", title: "Warehouse Management System", basePrice: 37500, accent: "#7dc9a0",
    timeline: "8–10 weeks", deploy: "Web / IIS",
    description: "Industrial-grade stock control built for warehouse scale.",
    features: ["Stock control & tracking","Supplier management","Barcode scanning","Real-time alerts","Operational reports"],
    addons: [
      { addonKey:"wh1",  label:"Multi-Warehouse Support",          price:5000, category:"Inventory",    description:"Manage inventory across multiple warehouse locations from one unified dashboard." },
      { addonKey:"wh2",  label:"Batch & Lot Tracking",             price:3500, category:"Inventory",    description:"Track production batches and lot numbers with full expiry and traceability per batch." },
      { addonKey:"wh3",  label:"Serial Number Tracking",           price:3000, category:"Inventory",    description:"Assign and track unique serial numbers per unit — essential for electronics and equipment." },
      { addonKey:"wh4",  label:"Expiry Date Monitoring",           price:2500, category:"Inventory",    description:"Get automated alerts before stock expires. Critical for food, pharma, and perishables." },
      { addonKey:"wh5",  label:"Safety Stock Automation",          price:3000, category:"Inventory",    description:"Auto-compute reorder buffer levels and trigger purchase requests before stockout occurs." },
      { addonKey:"wh6",  label:"Stock Reservation System",         price:3000, category:"Inventory",    description:"Reserve specific inventory for confirmed orders, preventing allocation conflicts." },
      { addonKey:"wh7",  label:"Inventory Auditing Tools",         price:2500, category:"Inventory",    description:"Cycle count tools, variance reconciliation, and physical count management built in." },
      { addonKey:"wh8",  label:"Barcode Scanning",                 price:3500, category:"Scanning",     description:"Scan barcodes on receiving, picking, and dispatch to eliminate manual entry errors." },
      { addonKey:"wh9",  label:"QR Code Label Generation",         price:2000, category:"Scanning",     description:"Generate and print QR code labels for products, bins, and shelving locations." },
      { addonKey:"wh10", label:"Mobile Scanner App",               price:3000, category:"Scanning",     description:"Use any Android phone as a warehouse scanner — no dedicated hardware required." },
      { addonKey:"wh11", label:"Purchase Order System",            price:3000, category:"Orders",       description:"Create, send, and track purchase orders with supplier confirmation and receiving workflows." },
      { addonKey:"wh12", label:"Returns Management (RMA)",         price:3500, category:"Orders",       description:"Handle customer and supplier returns with inspection, restocking, and credit note workflows." },
      { addonKey:"wh13", label:"Backorder Management",             price:2500, category:"Orders",       description:"Track and fulfill orders automatically when out-of-stock items are replenished." },
      { addonKey:"wh14", label:"Pick & Pack Workflow",             price:3500, category:"Orders",       description:"Guided picking lists, packing confirmation, and weight/dimension logging per shipment." },
      { addonKey:"wh15", label:"Delivery & Dispatch Tracking",     price:3500, category:"Logistics",    description:"Log outbound deliveries with driver assignment, status updates, and proof of delivery." },
      { addonKey:"wh16", label:"Shipping Label Automation",        price:2500, category:"Logistics",    description:"Auto-generate shipping labels with courier format (J&T, LBC, Lalamove) on dispatch." },
      { addonKey:"wh17", label:"Freight Cost Calculator",          price:2000, category:"Logistics",    description:"Compute estimated shipping costs by weight, dimension, and destination before dispatch." },
      { addonKey:"wh18", label:"Courier Integration",              price:4000, category:"Logistics",    description:"Live status sync with local couriers (J&T, LBC, Flash, Ninja Van) via API." },
      { addonKey:"wh19", label:"Warehouse Analytics Dashboard",    price:4500, category:"Analytics",    description:"Real-time overview of stock levels, turnover rates, and warehouse performance KPIs." },
      { addonKey:"wh20", label:"Stock Movement Reports",           price:3000, category:"Analytics",    description:"Full audit trail of every stock movement — inbound, outbound, transfers, and adjustments." },
      { addonKey:"wh21", label:"Dead Stock & Aging Reports",       price:3000, category:"Analytics",    description:"Identify slow-moving and obsolete inventory to free up space and recover capital." },
      { addonKey:"wh22", label:"Demand Forecasting Report",        price:4000, category:"Analytics",    description:"Predict future stock needs from historical consumption patterns and seasonal trends." },
      { addonKey:"wh23", label:"Supplier Performance Report",      price:3000, category:"Analytics",    description:"Score suppliers on lead time, fill rate, and pricing accuracy over any date range." },
      { addonKey:"wh24", label:"Stock Valuation Report (FIFO/AVG)",price:3500, category:"Analytics",    description:"Calculate total inventory value using FIFO or weighted average cost methods." },
      { addonKey:"wh25", label:"Excel / PDF Export on All Reports",price:2000, category:"Analytics",    description:"Export any report or table to formatted Excel or branded PDF with one click." },
      { addonKey:"wh26", label:"Employee Time & Attendance",       price:3000, category:"Workforce",    description:"Shift scheduling, DTR logging, and overtime tracking for warehouse staff." },
      { addonKey:"wh27", label:"Task Assignment System",           price:2500, category:"Workforce",    description:"Assign warehouse jobs to specific workers with deadline tracking and completion status." },
      { addonKey:"wh28", label:"Productivity Tracking",            price:3000, category:"Workforce",    description:"Measure picks-per-hour, error rates, and fulfillment speed per warehouse employee." },
      { addonKey:"wh29", label:"Shopee / Lazada Integration",      price:5000, category:"Integrations", description:"Sync product listings, orders, and inventory in real-time with Shopee and Lazada stores." },
      { addonKey:"wh30", label:"Shopify / WooCommerce Sync",       price:5000, category:"Integrations", description:"Two-way inventory and order sync with your Shopify or WooCommerce online store." },
      { addonKey:"wh31", label:"POS Integration",                  price:4000, category:"Integrations", description:"Connect to your retail POS system so in-store sales automatically deduct from warehouse stock." },
      { addonKey:"wh32", label:"Accounting System Export",         price:3500, category:"Integrations", description:"Push purchase orders, invoices, and stock valuations directly to QuickBooks or Xero." },
      { addonKey:"wh33", label:"API Access",                       price:4500, category:"Integrations", description:"Full REST API access to connect any external system — ERP, 3PL, or custom apps." },
      { addonKey:"wh34", label:"Role-Based Access Control",        price:2500, category:"Security",     description:"Granular permission levels per user — restrict access to sensitive data by role." },
      { addonKey:"wh35", label:"Audit Logs",                       price:2000, category:"Security",     description:"Full user activity history — every action logged with timestamp and user ID." },
      { addonKey:"wh36", label:"Backup & Data Recovery",           price:2500, category:"Security",     description:"Automated daily backups with one-click restore — your data is never lost." },
      { addonKey:"wh37", label:"Mobile Warehouse App",             price:4000, category:"Mobile",       description:"Dedicated Android/iOS app for warehouse staff — scan, receive, and dispatch on the go." },
      { addonKey:"wh38", label:"Offline Mode",                     price:3500, category:"Mobile",       description:"Continue warehouse operations without internet — syncs automatically when reconnected." },
      { addonKey:"wh39", label:"Multi-Language Support",           price:2000, category:"Mobile",       description:"Switch system language between Filipino, English, and other supported locales." },
      { addonKey:"wh40", label:"AI Demand Forecasting",            price:8000, category:"AI",           description:"Machine learning model that predicts stock needs based on sales trends, seasonality, and lead times." },
      { addonKey:"wh41", label:"AI Slotting Optimization",         price:6000, category:"AI",           description:"Intelligently suggest optimal product placement in the warehouse to minimize pick travel time." },
      { addonKey:"wh42", label:"Predictive Restock Alerts",        price:5000, category:"AI",           description:"AI-powered alerts that flag which items will run out before manual thresholds are triggered." },
      { addonKey:"wh43", label:"Supplier Invoice Tracking",        price:2500, category:"Finance",      description:"Match supplier invoices to purchase orders and track payment status per delivery." },
      { addonKey:"wh44", label:"Landed Cost Tracking",             price:3000, category:"Finance",      description:"Allocate freight, customs, and handling costs to the correct inventory items on import." },
    ],
  },
  {
    tag: "Inventory", title: "Inventory Control System", basePrice: 27000, accent: "#8fc99a",
    timeline: "6–8 weeks", deploy: "Web / Desktop",
    description: "Real-time stock visibility in one unified platform.",
    features: ["Stock tracking","Auto-reorder logic","Purchase orders","Sales analytics","Low-stock alerts"],
    addons: [
      { addonKey:"inv1",  label:"Multi-Warehouse Management",       price:8000,  category:"Core",          description:"Manage multiple warehouse branches with per-location stock visibility and transfers." },
      { addonKey:"inv2",  label:"Real-Time Inventory Sync",         price:5000,  category:"Core",          description:"Instant stock updates across all locations and channels as transactions occur." },
      { addonKey:"inv3",  label:"Batch & Lot Tracking",             price:6000,  category:"Core",          description:"Track production batches and lot numbers for full traceability and recall management." },
      { addonKey:"inv4",  label:"Serial Number Tracking",           price:5000,  category:"Core",          description:"Assign and track unique serial numbers per item for warranty and support management." },
      { addonKey:"inv5",  label:"Expiry Date & Shelf-life Monitoring",price:4000,category:"Core",          description:"Track expiry dates per batch. Auto-flag items approaching or past their shelf-life." },
      { addonKey:"inv6",  label:"Inventory Forecasting",            price:9000,  category:"Core",          description:"AI-powered demand forecasting to predict restocking needs and reduce overstock." },
      { addonKey:"inv7",  label:"Safety Stock Automation",          price:4500,  category:"Core",          description:"Automatically compute and maintain safety stock levels based on lead time and demand." },
      { addonKey:"inv8",  label:"Inventory Auditing",               price:4000,  category:"Core",          description:"Scheduled and ad-hoc stock verification with variance reporting and discrepancy logs." },
      { addonKey:"inv9",  label:"Stock Reservation",                price:4500,  category:"Core",          description:"Reserve inventory for confirmed sales or production orders to prevent overselling." },
      { addonKey:"inv10", label:"Consignment Inventory",            price:6000,  category:"Core",          description:"Manage supplier-owned stock on your premises with consignment accounting." },
      { addonKey:"inv11", label:"Barcode Scanning",                 price:3500,  category:"Barcode & RFID", description:"Scan barcodes for fast receiving, picking, and inventory counting." },
      { addonKey:"inv12", label:"Advanced Barcode Automation",      price:7000,  category:"Barcode & RFID", description:"Automated scanning workflows for receiving, putaway, picking, and shipping." },
      { addonKey:"inv13", label:"QR Code Management",               price:3500,  category:"Barcode & RFID", description:"Generate and print QR labels for products, bins, and locations." },
      { addonKey:"inv14", label:"Mobile Scanner App",               price:4000,  category:"Barcode & RFID", description:"Use a smartphone camera as a scanner for inventory operations on the floor." },
      { addonKey:"inv15", label:"Order Management System",          price:6000,  category:"Orders",        description:"Centralized order management from creation to fulfillment with status tracking." },
      { addonKey:"inv16", label:"Pick & Pack Automation",           price:7000,  category:"Orders",        description:"Automated packing workflow with pick lists, bin locations, and packing verification." },
      { addonKey:"inv17", label:"Returns Management (RMA)",         price:5000,  category:"Orders",        description:"Product return handling with RMA numbers, inspection workflow, and restocking." },
      { addonKey:"inv18", label:"Backorder Management",             price:4000,  category:"Orders",        description:"Auto-manage out-of-stock orders with backorder queues and fulfillment scheduling." },
      { addonKey:"inv19", label:"POS Integration",                  price:5000,  category:"Orders",        description:"Sync retail POS sales in real-time with inventory deduction and reconciliation." },
      { addonKey:"inv20", label:"Courier Integration (J&T/LBC/DHL)",price:5000, category:"Shipping",      description:"Connect with J&T, LBC, DHL — auto-book pickups and generate waybills." },
      { addonKey:"inv21", label:"Real-Time Shipment Tracking",      price:4500,  category:"Shipping",      description:"Live delivery tracking synced from courier APIs into your order records." },
      { addonKey:"inv22", label:"Shipping Label Automation",        price:3500,  category:"Shipping",      description:"Auto-generate and print shipping labels with order data and courier barcodes." },
      { addonKey:"inv23", label:"Freight Cost Calculator",          price:3500,  category:"Shipping",      description:"Compute shipping cost at checkout or order creation based on weight and destination." },
      { addonKey:"inv24", label:"Purchase Order System",            price:4500,  category:"Procurement",   description:"Full PO workflow — create, approve, receive, and match against invoices." },
      { addonKey:"inv25", label:"Supplier Portal",                  price:6000,  category:"Procurement",   description:"Vendor collaboration portal for quote submission, PO acknowledgment, and invoicing." },
      { addonKey:"inv26", label:"Supplier Price Comparison",        price:4000,  category:"Procurement",   description:"Compare vendor quotations side-by-side to select the best price and lead time." },
      { addonKey:"inv27", label:"Approval Workflow",                price:3500,  category:"Procurement",   description:"Multi-level purchase approval routing with email notifications and audit trail." },
      { addonKey:"inv28", label:"Vendor Performance Tracking",      price:4000,  category:"Procurement",   description:"Score suppliers on delivery, quality, and pricing with performance dashboards." },
      { addonKey:"inv29", label:"Accounting Integration",           price:6000,  category:"Finance",       description:"Sync inventory values and COGS with QuickBooks, Xero, or custom accounting." },
      { addonKey:"inv30", label:"Cost Tracking",                    price:4500,  category:"Finance",       description:"Track landed costs, carrying costs, and COGS per product and category." },
      { addonKey:"inv31", label:"Tax Management",                   price:3500,  category:"Finance",       description:"VAT/EVAT computation on purchases and sales with BIR-compliant tax reports." },
      { addonKey:"inv32", label:"Purchase Invoice Generation",      price:3000,  category:"Invoices",      description:"Auto-generate supplier invoices from received POs with PDF export." },
      { addonKey:"inv33", label:"Supplier Performance Report",      price:3000,  category:"Invoices",      description:"Printable supplier KPI report with delivery accuracy, lead time, and pricing trends." },
      { addonKey:"inv34", label:"Stock Valuation Report (FIFO/AVG)",price:3500,  category:"Invoices",      description:"Generate stock valuation reports using FIFO or weighted average costing methods." },
      { addonKey:"inv35", label:"Excel / PDF Export on All Reports",price:2000,  category:"Invoices",      description:"One-click export of any report to Excel or PDF for sharing and archiving." },
      { addonKey:"inv36", label:"Shopee Integration",               price:5000,  category:"E-commerce",    description:"Sync Shopee orders and auto-deduct inventory upon order confirmation." },
      { addonKey:"inv37", label:"Lazada Integration",               price:5000,  category:"E-commerce",    description:"Sync Lazada orders and inventory levels in real-time via Lazada API." },
      { addonKey:"inv38", label:"TikTok Shop Integration",          price:5000,  category:"E-commerce",    description:"Connect TikTok Shop orders to inventory for live stock sync and fulfillment." },
      { addonKey:"inv39", label:"Shopify / WooCommerce Integration",price:5500,  category:"E-commerce",    description:"Bi-directional sync with Shopify or WooCommerce for orders and stock levels." },
      { addonKey:"inv40", label:"Inventory Analytics Dashboard",    price:5000,  category:"Dashboard",     description:"Real-time KPI dashboard — stock levels, turnover rate, and reorder status." },
      { addonKey:"inv41", label:"Sales vs Stock Analytics",         price:4000,  category:"Data Analysis",  description:"Compare sales velocity against current stock levels with trend charts." },
      { addonKey:"inv42", label:"Custom BI Reports",                price:7000,  category:"Data Analysis",  description:"Build custom inventory reports with filters, grouping, and chart types." },
      { addonKey:"inv43", label:"Dead Stock & Slow-Mover Report",   price:3000,  category:"Data Analysis",  description:"Identify products with no movement for a set period to reduce carrying costs." },
      { addonKey:"inv44", label:"Automated Scheduled Reports",      price:3000,  category:"Data Analysis",  description:"Schedule daily, weekly, or monthly reports to be auto-emailed to stakeholders." },
      { addonKey:"inv45", label:"Role-Based Access Control",        price:3500,  category:"Security",      description:"Define granular permissions per user role — view, edit, approve, export." },
      { addonKey:"inv46", label:"Full Audit Logs",                  price:3000,  category:"Security",      description:"Track every inventory action — who did what, when, and on which item." },
      { addonKey:"inv47", label:"Data Backup & Recovery",           price:3500,  category:"Security",      description:"Automated daily backups with point-in-time recovery and export." },
      { addonKey:"inv48", label:"Mobile Inventory App",             price:6000,  category:"Mobile",        description:"Android/iOS app for stock counting, receiving, and transfers on the warehouse floor." },
      { addonKey:"inv49", label:"Offline Mode",                     price:5000,  category:"Mobile",        description:"Full offline inventory access with automatic sync when connectivity returns." },
      { addonKey:"inv50", label:"API Access",                       price:8000,  category:"Mobile",        description:"REST API with key auth for connecting with ERP, POS, or third-party platforms." },
    ],
  },
  {
    tag: "CRM", title: "CRM System", basePrice: 30000, accent: "#fcd34d",
    timeline: "7–9 weeks", deploy: "Web",
    description: "Manage leads and clients from pipeline to close.",
    features: ["Lead tracking","Client history","Follow-up reminders","Sales pipeline","Activity logs"],
    addons: [
      { addonKey:"crm_c1",  label:"Lead Management",                price:3500,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c2",  label:"Customer Database",              price:3500,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c3",  label:"Contact Management",             price:2500,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c4",  label:"Opportunity Management",         price:6000,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c5",  label:"Deal Tracking",                  price:3500,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c6",  label:"Customer Segmentation",          price:3500,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c7",  label:"Activity Timeline",              price:3000,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c8",  label:"Notes & Attachments",            price:2000,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c9",  label:"Task & Reminder System",         price:2500,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c10", label:"Calendar Integration",           price:3500,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c11", label:"Sales Pipeline Visualization",   price:6000,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c12", label:"Custom CRM Fields",              price:3000,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c13", label:"Duplicate Detection",            price:2800,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c14", label:"CRM Workflow Automation",        price:7000,   category:"Core CRM",   description:"" },
      { addonKey:"crm_c15", label:"Customer 360 View",              price:6000,   category:"Core CRM",   description:"" },
      { addonKey:"crm_s1",  label:"Sales Automation Engine",        price:9000,   category:"Sales",      description:"" },
      { addonKey:"crm_s2",  label:"Quotation Generator",            price:3500,   category:"Sales",      description:"" },
      { addonKey:"crm_s3",  label:"Invoice Integration",            price:3000,   category:"Sales",      description:"" },
      { addonKey:"crm_s4",  label:"Proposal Management",            price:5000,   category:"Sales",      description:"" },
      { addonKey:"crm_s5",  label:"Commission Tracking",            price:5000,   category:"Sales",      description:"" },
      { addonKey:"crm_s6",  label:"Territory Management",           price:5500,   category:"Sales",      description:"" },
      { addonKey:"crm_s7",  label:"Sales Forecasting",              price:9000,   category:"Sales",      description:"" },
      { addonKey:"crm_s8",  label:"Sales KPI Tracking",             price:4500,   category:"Sales",      description:"" },
      { addonKey:"crm_s9",  label:"Product Catalog Integration",    price:3000,   category:"Sales",      description:"" },
      { addonKey:"crm_s10", label:"CPQ System",                     price:18000,  category:"Sales",      description:"" },
      { addonKey:"crm_m1",  label:"Email Marketing",                price:5000,   category:"Marketing",  description:"" },
      { addonKey:"crm_m2",  label:"SMS Marketing",                  price:4500,   category:"Marketing",  description:"" },
      { addonKey:"crm_m3",  label:"WhatsApp Integration",           price:5000,   category:"Marketing",  description:"" },
      { addonKey:"crm_m4",  label:"Social Media Integration",       price:5000,   category:"Marketing",  description:"" },
      { addonKey:"crm_m5",  label:"Marketing Automation Workflows", price:8000,   category:"Marketing",  description:"" },
      { addonKey:"crm_m6",  label:"Campaign Management",            price:5000,   category:"Marketing",  description:"" },
      { addonKey:"crm_m7",  label:"Landing Page Builder",           price:5000,   category:"Marketing",  description:"" },
      { addonKey:"crm_m8",  label:"Lead Capture Forms",             price:2800,   category:"Marketing",  description:"" },
      { addonKey:"crm_m9",  label:"Pop-Up & Exit Intent Tools",     price:2800,   category:"Marketing",  description:"" },
      { addonKey:"crm_m10", label:"Drip Email Campaigns",           price:5000,   category:"Marketing",  description:"" },
      { addonKey:"crm_m11", label:"Newsletter System",              price:3000,   category:"Marketing",  description:"" },
      { addonKey:"crm_m12", label:"Marketing Analytics",            price:5000,   category:"Marketing",  description:"" },
      { addonKey:"crm_h1",  label:"Ticketing System",               price:5000,   category:"Support",    description:"" },
      { addonKey:"crm_h2",  label:"Live Chat Support",              price:5000,   category:"Support",    description:"" },
      { addonKey:"crm_h3",  label:"Omnichannel Support",            price:9000,   category:"Support",    description:"" },
      { addonKey:"crm_h4",  label:"Knowledge Base",                 price:5000,   category:"Support",    description:"" },
      { addonKey:"crm_h5",  label:"SLA Management",                 price:5000,   category:"Support",    description:"" },
      { addonKey:"crm_h6",  label:"Customer Satisfaction Surveys",  price:3000,   category:"Support",    description:"" },
      { addonKey:"crm_h7",  label:"Call Center Integration",        price:9000,   category:"Support",    description:"" },
      { addonKey:"crm_h8",  label:"Chatbot Integration",            price:6000,   category:"Support",    description:"" },
      { addonKey:"crm_h9",  label:"Video Call Integration",         price:5000,   category:"Support",    description:"" },
      { addonKey:"crm_h10", label:"Remote Assistance Tools",        price:9000,   category:"Support",    description:"" },
      { addonKey:"crm_e1",  label:"Shopify Integration",            price:3500,   category:"E-commerce", description:"" },
      { addonKey:"crm_e2",  label:"WooCommerce Integration",        price:3500,   category:"E-commerce", description:"" },
      { addonKey:"crm_e3",  label:"Lazada Integration",             price:5000,   category:"E-commerce", description:"" },
      { addonKey:"crm_e4",  label:"Shopee Integration",             price:5000,   category:"E-commerce", description:"" },
      { addonKey:"crm_e5",  label:"POS Integration",                price:5000,   category:"E-commerce", description:"" },
      { addonKey:"crm_e6",  label:"Customer Purchase Tracking",     price:3000,   category:"E-commerce", description:"" },
      { addonKey:"crm_e7",  label:"Abandoned Cart Recovery",        price:5000,   category:"E-commerce", description:"" },
      { addonKey:"crm_e8",  label:"Loyalty Rewards Integration",    price:5000,   category:"E-commerce", description:"" },
      { addonKey:"crm_e9",  label:"Ecommerce Analytics",            price:4500,   category:"E-commerce", description:"" },
      { addonKey:"crm_a1",  label:"AI CRM Assistant",               price:7000,   category:"AI",         description:"" },
      { addonKey:"crm_a2",  label:"AI Lead Scoring",                price:9000,   category:"AI",         description:"" },
      { addonKey:"crm_a3",  label:"AI Sales Prediction",            price:12000,  category:"AI",         description:"" },
      { addonKey:"crm_a4",  label:"AI Chatbot",                     price:7000,   category:"AI",         description:"" },
      { addonKey:"crm_a5",  label:"AI Email Writer",                price:5000,   category:"AI",         description:"" },
      { addonKey:"crm_a6",  label:"AI Sentiment Analysis",          price:12000,  category:"AI",         description:"" },
      { addonKey:"crm_a7",  label:"AI Recommendation Engine",       price:9000,   category:"AI",         description:"" },
      { addonKey:"crm_a8",  label:"Workflow Automation Engine",     price:8000,   category:"AI",         description:"" },
      { addonKey:"crm_a9",  label:"Predictive Customer Analytics",  price:12000,  category:"AI",         description:"" },
      { addonKey:"crm_r1",  label:"CRM Dashboard",                  price:4500,   category:"Analytics",  description:"" },
      { addonKey:"crm_r2",  label:"Sales Reports",                  price:3000,   category:"Analytics",  description:"" },
      { addonKey:"crm_r3",  label:"Lead Conversion Reports",        price:4500,   category:"Analytics",  description:"" },
      { addonKey:"crm_r4",  label:"Customer Lifetime Value Reports",price:5000,   category:"Analytics",  description:"" },
      { addonKey:"crm_r5",  label:"Employee Performance Reports",   price:4500,   category:"Analytics",  description:"" },
      { addonKey:"crm_r6",  label:"Marketing ROI Reports",          price:4500,   category:"Analytics",  description:"" },
      { addonKey:"crm_r7",  label:"AI Predictive Analytics",        price:12000,  category:"Analytics",  description:"" },
      { addonKey:"crm_r8",  label:"Automated Reports",              price:2800,   category:"Analytics",  description:"" },
      { addonKey:"crm_r9",  label:"Real-Time Monitoring",           price:4500,   category:"Analytics",  description:"" },
      { addonKey:"crm_acc1",label:"Accounting Integration",         price:5500,   category:"ERP",        description:"" },
      { addonKey:"crm_acc2",label:"QuickBooks Integration",         price:3500,   category:"ERP",        description:"" },
      { addonKey:"crm_acc3",label:"Xero Integration",               price:3500,   category:"ERP",        description:"" },
      { addonKey:"crm_acc4",label:"SAP Integration",                price:25000,  category:"ERP",        description:"" },
      { addonKey:"crm_acc5",label:"Oracle Integration",             price:25000,  category:"ERP",        description:"" },
      { addonKey:"crm_acc6",label:"Inventory Integration",          price:5000,   category:"ERP",        description:"" },
      { addonKey:"crm_acc7",label:"Procurement Integration",        price:5000,   category:"ERP",        description:"" },
      { addonKey:"crm_mob1",label:"Mobile CRM App",                 price:6000,   category:"Mobile",     description:"" },
      { addonKey:"crm_mob2",label:"Cloud Hosting",                  price:5000,   category:"Mobile",     description:"" },
      { addonKey:"crm_mob3",label:"Offline CRM Mode",               price:5000,   category:"Mobile",     description:"" },
      { addonKey:"crm_mob4",label:"API Access",                     price:5500,   category:"Mobile",     description:"" },
      { addonKey:"crm_mob5",label:"White Label Branding",           price:8000,   category:"Mobile",     description:"" },
      { addonKey:"crm_mob6",label:"Multi-Device Sync",              price:2800,   category:"Mobile",     description:"" },
      { addonKey:"crm_mob7",label:"Custom Domain Setup",            price:2500,   category:"Mobile",     description:"" },
      { addonKey:"crm_sec1",label:"Role-Based Access Control",      price:2500,   category:"Security",   description:"" },
      { addonKey:"crm_sec2",label:"Audit Logs",                     price:2000,   category:"Security",   description:"" },
      { addonKey:"crm_sec3",label:"Data Encryption",                price:5000,   category:"Security",   description:"" },
      { addonKey:"crm_sec4",label:"Two-Factor Authentication",      price:3000,   category:"Security",   description:"" },
      { addonKey:"crm_sec5",label:"Backup & Disaster Recovery",     price:5000,   category:"Security",   description:"" },
      { addonKey:"crm_sec6",label:"Electronic Signature Support",   price:5000,   category:"Security",   description:"" },
      { addonKey:"crm_sec7",label:"GDPR/Data Privacy Compliance",   price:12000,  category:"Security",   description:"" },
    ],
  },
  {
    tag: "Booking", title: "Booking & Appointment System", basePrice: 22500, accent: "#b8a0d4",
    timeline: "5–7 weeks", deploy: "Web",
    description: "Online scheduling built for clinics and salons.",
    features: ["Online scheduling","SMS/email reminders","Staff calendar","Client management","Walk-in support"],
    addons: [
      { addonKey:"bk1", label:"SMS / Email Reminders",        price:3000, category:"Automation",    description:"" },
      { addonKey:"bk2", label:"Walk-in Queue Management",     price:2500, category:"Operations",    description:"" },
      { addonKey:"bk3", label:"Booking Analytics Dashboard",  price:3500, category:"Dashboard",     description:"" },
      { addonKey:"bk4", label:"Revenue & No-show Reports",    price:2500, category:"Data Analysis",  description:"" },
      { addonKey:"bk5", label:"Service Invoice Generation",   price:2000, category:"Invoices",      description:"" },
      { addonKey:"bk6", label:"Multi-staff / Multi-branch",   price:4000, category:"Operations",    description:"" },
      { addonKey:"bk7", label:"PayMongo Deposit Collection",  price:3500, category:"Finance",       description:"" },
      { addonKey:"bk8", label:"Client Loyalty Points",        price:3000, category:"E-commerce",    description:"" },
    ],
  },
  {
    tag: "Finance", title: "Invoice & Emailing System", basePrice: 18000, accent: "#c4b5fd",
    timeline: "5–6 weeks", deploy: "Web",
    description: "Generate, send, and track invoices all in one flow.",
    features: ["Invoice generation","Instant email sending","Payment tracking","PDF export","Reminder automation"],
    addons: [
      { addonKey:"fi1",  label:"Custom Invoice Templates",       price:3500,  category:"Core Invoice",   description:"Personalized invoice designs with your branding, logo, and color scheme." },
      { addonKey:"fi2",  label:"PDF Export with Branding",       price:2000,  category:"Core Invoice",   description:"One-click PDF generation with your company header and signature field." },
      { addonKey:"fi3",  label:"Recurring Invoice Schedules",    price:2500,  category:"Core Invoice",   description:"Auto-generate and send invoices on set intervals — weekly, monthly, or custom." },
      { addonKey:"fi4",  label:"Quotation & Proforma Invoices",  price:3000,  category:"Core Invoice",   description:"Convert quotations and proforma invoices directly into finalized billing." },
      { addonKey:"fi5",  label:"Credit & Debit Notes",           price:2800,  category:"Core Invoice",   description:"Refund and adjustment notes linked to original invoices for clean audit trails." },
      { addonKey:"fi6",  label:"Discount & Promo Management",    price:2000,  category:"Core Invoice",   description:"Line-item discounts, percentage or fixed, with promo code support." },
      { addonKey:"fi7",  label:"Multi-Currency Support",         price:3500,  category:"Core Invoice",   description:"Bill international clients in their currency with live exchange rate handling." },
      { addonKey:"fi8",  label:"Purchase Invoice Tracking",      price:3500,  category:"Core Invoice",   description:"Log and track supplier invoices against purchase orders and delivery receipts." },
      { addonKey:"fi9",  label:"Invoice Approval Workflow",      price:5000,  category:"Core Invoice",   description:"Multi-level approval routing before invoices are sent — department head, finance." },
      { addonKey:"fi10", label:"Multi-Branch / Multi-Company",   price:5500,  category:"Core Invoice",   description:"Manage invoicing across multiple branches or business entities from one dashboard." },
      { addonKey:"fi11", label:"Automated Invoice Emails",       price:2500,  category:"Email",          description:"Auto-send invoices immediately upon creation or on a scheduled trigger." },
      { addonKey:"fi12", label:"Payment Reminder Emails",        price:2000,  category:"Email",          description:"Automatic follow-up emails on due date, 3 days after, and 7 days overdue." },
      { addonKey:"fi13", label:"Custom Email Templates",         price:2800,  category:"Email",          description:"Branded email layouts for invoices, reminders, and receipts." },
      { addonKey:"fi14", label:"SMS Notifications",              price:3500,  category:"Email",          description:"SMS alerts to clients for invoice sent, payment due, and payment received." },
      { addonKey:"fi15", label:"Email Open & Click Tracking",    price:4000,  category:"Email",          description:"Know exactly when a client opened your invoice email and clicked payment links." },
      { addonKey:"fi16", label:"WhatsApp Invoice Alerts",        price:5000,  category:"Email",          description:"Send invoice notifications and payment reminders directly via WhatsApp Business API." },
      { addonKey:"fi17", label:"Bulk Email Sending",             price:3500,  category:"Email",          description:"Send invoices or reminders to hundreds of clients simultaneously." },
      { addonKey:"fi18", label:"PayMongo Payment Links",         price:3000,  category:"Payments",       description:"Shareable payment URLs that let clients pay directly via GCash, Maya, or card." },
      { addonKey:"fi19", label:"GCash Integration",              price:4500,  category:"Payments",       description:"Accept GCash payments directly linked to your invoices." },
      { addonKey:"fi20", label:"Maya Integration",               price:4500,  category:"Payments",       description:"Accept Maya (PayMaya) payments with automatic payment status update." },
      { addonKey:"fi21", label:"Bank Transfer Integration",      price:5000,  category:"Payments",       description:"Provide bank transfer details per invoice with payment confirmation uploads." },
      { addonKey:"fi22", label:"Installment Billing",            price:5500,  category:"Payments",       description:"Split invoices into scheduled partial payments with automatic tracking." },
      { addonKey:"fi23", label:"Subscription Billing",           price:6000,  category:"Payments",       description:"Recurring subscription charges with automatic invoice and payment collection." },
      { addonKey:"fi24", label:"Auto Payment Reconciliation",    price:8000,  category:"Payments",       description:"Automatically match incoming payments to open invoices and close them." },
      { addonKey:"fi25", label:"Revenue Dashboard",              price:3500,  category:"Dashboard",      description:"Live KPI overview — total billed, collected, outstanding, and overdue at a glance." },
      { addonKey:"fi26", label:"Sales & Tax Reports",            price:3000,  category:"Data Analysis",  description:"Invoice sales summaries and VAT/BIR-ready tax breakdown reports." },
      { addonKey:"fi27", label:"Overdue & Aging Reports",        price:2500,  category:"Data Analysis",  description:"Aging buckets (0-30, 31-60, 61-90 days) for receivables collection management." },
      { addonKey:"fi28", label:"Customer Payment Reports",       price:3000,  category:"Data Analysis",  description:"Client-level payment history, average payment days, and overdue frequency." },
      { addonKey:"fi29", label:"Cash Flow Forecasting",          price:6000,  category:"Data Analysis",  description:"Revenue prediction based on outstanding invoices, payment patterns, and schedules." },
      { addonKey:"fi30", label:"Scheduled Auto Reports",         price:2500,  category:"Data Analysis",  description:"Auto-generate and email financial reports weekly or monthly without manual action." },
      { addonKey:"fi31", label:"Client Payment Portal",          price:4000,  category:"Portal",         description:"Self-service portal where clients view invoices, payment history, and download receipts." },
      { addonKey:"fi32", label:"Digital Signature Support",      price:4500,  category:"Portal",         description:"Clients can e-sign invoices and contracts directly in the portal." },
      { addonKey:"fi33", label:"Role-Based Access Control",      price:2500,  category:"Portal",         description:"Separate access for Admin, Accountant, Sales, and View-only roles." },
      { addonKey:"fi34", label:"Audit Logs",                     price:2000,  category:"Portal",         description:"Full history of every invoice action — created, edited, sent, paid, voided." },
      { addonKey:"fi35", label:"VAT / BIR Tax Filing Reports",   price:5000,  category:"Accounting",     description:"BIR-compliant VAT returns, 2550M/Q, and tax certificate generation." },
      { addonKey:"fi36", label:"Expense Tracking",               price:3500,  category:"Accounting",     description:"Log and categorize business expenses against projects or cost centers." },
      { addonKey:"fi37", label:"Profit & Loss Reports",          price:4500,  category:"Accounting",     description:"Simple P&L statements generated from invoiced revenue and tracked expenses." },
      { addonKey:"fi38", label:"QuickBooks / Xero Sync",         price:5000,  category:"Accounting",     description:"Two-way sync of invoices, payments, and clients with QuickBooks or Xero." },
      { addonKey:"fi39", label:"AI Invoice Generator",           price:8000,  category:"AI",             description:"AI fills invoice details based on client history, past transactions, and templates." },
      { addonKey:"fi40", label:"AI Payment Prediction",          price:9000,  category:"AI",             description:"Predict which clients are likely to pay late based on behavior patterns." },
      { addonKey:"fi41", label:"Automated Workflow Engine",      price:7500,  category:"AI",             description:"Set rules to auto-send, auto-remind, auto-escalate, and auto-close invoices." },
    ],
  },
  {
    tag: "Restaurant", title: "Restaurant Ordering System", basePrice: 27000, accent: "#fdba74",
    timeline: "6–8 weeks", deploy: "Web",
    description: "QR ordering and kitchen management for F&B operations.",
    features: ["QR-based menu","Kitchen order display","Table management","Daily sales reports","Order history"],
    addons: [
      { addonKey:"re1", label:"Advanced Kitchen Display (KDS)", price:3000, category:"Operations",   description:"" },
      { addonKey:"re2", label:"Table Management & Floor Plan",  price:2500, category:"Operations",   description:"" },
      { addonKey:"re3", label:"Restaurant Analytics Dashboard", price:4000, category:"Dashboard",    description:"" },
      { addonKey:"re4", label:"Best Seller & Menu Reports",     price:2500, category:"Data Analysis", description:"" },
      { addonKey:"re5", label:"Customer Receipt / Invoice",     price:1500, category:"Invoices",     description:"" },
      { addonKey:"re6", label:"Online Ordering (Delivery)",     price:5000, category:"E-commerce",   description:"" },
      { addonKey:"re7", label:"Loyalty & Promo System",         price:3000, category:"E-commerce",   description:"" },
      { addonKey:"re8", label:"Inventory Integration",          price:3500, category:"Operations",   description:"" },
      { addonKey:"re9", label:"PayMongo QR Payment",            price:3000, category:"Finance",      description:"" },
    ],
  },
];

async function main() {
  console.log("Seeding systems and addons...");

  for (const sys of systemsData) {
    const { addons, ...systemFields } = sys;

    const created = await prisma.system.upsert({
      where:  { tag: systemFields.tag },
      update: systemFields,
      create: systemFields,
    });

    console.log(`✓ System: ${created.title} (${addons.length} addons)`);

    for (const addon of addons) {
      await prisma.systemAddon.upsert({
        where:  { systemId_addonKey: { systemId: created.id, addonKey: addon.addonKey } },
        update: addon,
        create: { ...addon, systemId: created.id },
      });
    }
  }

  console.log("Done. All systems and addons seeded.");
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());